set noindex except for production
cloudnativedaysjp/dreamkast pull request #1029
Opened 2021-11-21 05:48 UTC by oke-py

closes #996

2021-11-21 05:50 UTC, showks-containerdaysjp commented
Review app

https://dreamkast-dk-1029.dev.cloudnativedays.jp

2021-11-21 08:31 UTC, inductor requested changes

2021-11-21 08:31 UTC, inductor commented on app/controllers/application_controller.rb
> +    env_name == "production"
これRailsの設定なので意味がない

https://github.com/cloudnativedaysjp/dreamkast-infra/blob/main/manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast.yaml#L34-L35

とるならこっちじゃないかな

https://github.com/cloudnativedaysjp/dreamkast-infra/blob/main/manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast.yaml#L48

2021-11-21 08:47 UTC, oke-py commented on app/controllers/application_controller.rb
> +    env_name == "production"
`env_name`はこちらです。
https://github.com/cloudnativedaysjp/dreamkast/blob/main/app/helpers/env_helper.rb
たしかに`DREAMKAST_NAMESPACE`を利用するのはよいかもですね。

2021-11-21 13:45 UTC, inductor commented on app/controllers/application_controller.rb
> +    env_name == "production"
envこんなのあったのね。しらんかった

2021-11-26 00:42 UTC, jacopen approved these changes
`env_name` を使う形で支障ないと思うのでLGTM

2021-11-26 02:15 UTC, inductor approved these changes

2021-11-27 00:21 UTC, merged