use PR number for IVS/MediaLive resource name
cloudnativedaysjp/dreamkast pull request #1035
Opened 2021-11-28 04:17 UTC by takaishi

fix https://github.com/cloudnativedaysjp/dreamkast/issues/1034

2021-11-28 04:19 UTC, showks-containerdaysjp commented
Review app

https://dreamkast-dk-1035.dev.cloudnativedays.jp

2021-12-01 08:21 UTC, jacopen requested changes

2021-12-01 08:21 UTC, jacopen commented on app/models/live_stream_ivs.rb
> +    name = env_name == "review_app" ? "review_app_#{review_app_number}" : env_name
`review_app?` があるのでそれを使った方がいいかなというのと、三項演算子使うよりはシンプルにこっちのほうが意図伝わりやすいかなと

```
if review_app?
  "review_app_#{review_app_number}_#{conference.abbr}_track#{track.name}"
else
  "#{env_name}_#{conference.abbr}_track#{track.name}"
end
```

2021-12-01 08:21 UTC, jacopen commented on app/models/live_stream_media_live.rb
> +    name = review_app? ? "review_app_#{review_app_number}" : env_name
ここもシンプルにifで分けた方が読みやすいかな～

2021-12-01 10:16 UTC, jacopen approved these changes

2021-12-01 10:16 UTC, merged