Control display video
cloudnativedaysjp/dreamkast pull request #1049
Opened 2021-12-12 07:50 UTC by takaishi

2021-12-12 07:52 UTC, showks-containerdaysjp commented
Review app

https://dreamkast-dk-1049.dev.cloudnativedays.jp

2021-12-18 09:14 UTC, takaishi commented
ん？クローズされている

2021-12-20 06:40 UTC, jacopen commented on app/controllers/talks_controller.rb
> +
nits: この空行追加いらないかも

2021-12-20 06:49 UTC, jacopen requested changes

2021-12-20 06:49 UTC, jacopen commented on app/controllers/talks_controller.rb
> +  def display_video?(conference, talk)
このメソッド、ヘルパーメソッドよりもtalkモデルに落としたほうが綺麗な気がしている。

理由1: Videoの表示非表示はtalkごとに付与される属性である
理由2: talk自体がconferenceに紐付いているので、このメソッドにconferenceを渡す必要なさそう(たとえばtalkと矛盾するconferenceを渡せてしまう)
理由3: フラグの書き方が綺麗になる

今の実装
```
<% if display_video?(conference, talk) %>
```

モデルに落とした場合
```
<% if talk.display_video? %>
```

2021-12-21 13:56 UTC, takaishi commented on app/controllers/talks_controller.rb
> +  def display_video?(conference, talk)
ログインしているかどうかも判定条件に使う必要があるので、ロジックを書く場所はモデルよりはコントローラーの方が適切じゃないかなあ。

talksがconferenceへの関連を持っているからconferenceを渡す必要はなさそうだね

2021-12-21 14:08 UTC, jacopen commented on app/controllers/talks_controller.rb
> +  def display_video?(conference, talk)
あー、なるほど。確かにログインしているかどうかはモデルからだと取りづらいか

2021-12-23 10:02 UTC, jacopen approved these changes

2021-12-23 10:02 UTC, merged