fix error when proposal is registered
cloudnativedaysjp/dreamkast pull request #1060
Opened 2021-12-23 10:41 UTC by takaishi

fix https://github.com/cloudnativedaysjp/dreamkast/issues/1052

2021-12-23 10:43 UTC, showks-containerdaysjp commented
Review app

https://dreamkast-dk-1060.dev.cloudnativedays.jp

2021-12-25 06:44 UTC, oshiro3 approved these changes
#1061 をローカルでマージして動作確認したところメールの受信を確認できました。

2021-12-25 06:44 UTC, oshiro3 commented on spec/mailers/speaker_mailer_spec.rb
> +  shared_examples_for :has_basic_information do
テストの追加ありがとうございます！（ぼくはなぜこれだけしか書いていなかったのだろうか。。。）

2021-12-25 07:23 UTC, oshiro3 requested changes
メールを確認したところ「想定受講者」以下に選択肢とか含めたすべての文言が改行無しで出てしまってますね

自分のローカルだとこんな感じでした！
![image](https://user-images.githubusercontent.com/40717789/147397886-cb44577b-f14b-4f76-8e98-87f2d2d6f74c.png)

2021-12-26 01:48 UTC, takaishi commented
テスト上だと改行されてるんだけどな…

2021-12-26 03:15 UTC, oshiro3 approved these changes
OKだと思います！
![image](https://user-images.githubusercontent.com/40717789/147398018-6f691238-26cc-4cd0-a72c-8df23c140c80.png)

2021-12-26 03:15 UTC, merged