エントリー後にSpeaker dashboardからpublic session pageを表示するとregistrationに飛ばされてしまう不具合の修正
cloudnativedaysjp/dreamkast pull request #1066
Opened 2021-12-26 05:37 UTC by oshiro3

## 現象

エントリー後にログイン状態でセッションリストを表示しようとするとユーザー登録にりだいれくとされてしまう問題があった

## 原因

`concern/Secured.rb`  の `new_user?` メソッドが Profile が無い状態ではリダイレクトするようになっていること

## 解決方法

`talks_controller.rb` で `new_user?` を再定義し、CFP 募集期間のみ Speaker 登録でもセッションリストを見れるようにした
できるだけ現行仕様を変更しないためとSpeakerの責任を大きくしないため CFP 募集期間のみの変更とした

2021-12-26 05:43 UTC, showks-containerdaysjp commented
Review app

https://dreamkast-dk-1066.dev.cloudnativedays.jp

2021-12-27 05:33 UTC, jacopen requested changes

2021-12-27 05:33 UTC, jacopen commented on app/controllers/talks_controller.rb
> +    (speaker? && set_conference.registered?) || super
`registered?` はCFP募集期間中だけでなく、一般参加者申し込み中にもこのステータスのままです

CFP募集期間中かどうかは `speaker_entry_enabled?`  で判断する形になります

2021-12-27 05:36 UTC, oshiro3 commented on app/controllers/talks_controller.rb
> +    (speaker? && set_conference.registered?) || super
承知しました。
conference のステータスが変わると思っていました。

2021-12-27 05:45 UTC, jacopen commented on app/controllers/talks_controller.rb
> +    (speaker? && set_conference.registered?) || super
このフラグ周り、見直したいですよねぇ・・・
自分もこのあたりが課題だと思っていて、こんな感じでカンファレンスステータスを整理したほうがいいんじゃないかという案をMiroにまとめていってます

https://miro.com/app/board/uXjVOb-gTrw=/?moveToWidget=3458764515081371247&cot=14

2021-12-27 06:04 UTC, oshiro3 commented on app/controllers/talks_controller.rb
> +    (speaker? && set_conference.registered?) || super
そうですね、なかなか複雑性が高くなっていそうかなーとは感じます。
conference の状態とそれによるアプリケーションの状態の対応関係が1対1じゃないのが難しそうかと思いました。
なのでコントローラや view が状態の管理を持ってしまっているという可能性があるので、その辺りのルールを持ったクラスがいても良いのかなと。
miro のマトリクスをコードにして持っているクラスがいるイメージです。

2021-12-27 06:39 UTC, jacopen approved these changes

2021-12-27 06:39 UTC, merged