先にLoginからAuth0ログインを行った後にエントリーを行おうとするとregistrationに飛ばされてしまう不具合の修正
cloudnativedaysjp/dreamkast pull request #1072
Opened 2021-12-26 13:23 UTC by oshiro3

## 現象

SSIA #1050 

## 原因

speaker form とガイダンスを表示する分岐が `logged in?` によって制御されているため、ログイン状態ではガイダンスが表示されなくなっていた。

## 解決方法

新たに `speakers/guidance` ルーティングを追加し、ログイン状態に関わらずガイダンスページを表示するようにした。
また、非ログイン状態でガイダンスからエントリーする際にサインアップ/サインインを行うが、その場合ガイダンスページに再度リダイレクトされてしまいUXを損ねる可能性があったため、`auth0` からのリダイレクトでガイダンスページにアクセスした時のみフォームにリダイレクトするように変更

2021-12-26 13:38 UTC, showks-containerdaysjp commented
Review app

https://dreamkast-dk-1072.dev.cloudnativedays.jp

2021-12-27 05:43 UTC, jacopen requested changes

2021-12-27 05:43 UTC, jacopen commented on app/views/event/partial/_speaker_entry_button.html.erb
> +  <%= link_to speaker_entry_button_name, speakers_guidance_path, {method: :get, class: "btn btn-entry btn-xl  m-2" } %>
おおよその動きは問題なさそう。

1つ気になるのが、ここは `speaker_entry_button_name` によって、既にエントリー済みの場合ボタンのラベルが変わり、 "スピーカーダッシュボード" と表示されるようになってます。

https://github.com/cloudnativedaysjp/dreamkast/blob/9d361dc8ee97e2a8df4bf0f5b4343d7c3b7aebb6/app/controllers/event_controller.rb#L42-L46

ただ、今回の場合スピーカーダッシュボードに飛ぶのではなくガイダンスページに飛ぶようになってしまうので、 `@speaker.present?` を見て飛ぶ先を変更するようにしたほうがいいかなと。

2021-12-27 06:46 UTC, oshiro3 commented on app/views/event/partial/_speaker_entry_button.html.erb
> +  <%= link_to speaker_entry_button_name, speakers_guidance_path, {method: :get, class: "btn btn-entry btn-xl  m-2" } %>
承知しました。
`speaker_entry_button_name` と同様の方法でリンク先を動的に設定するようにしました。

2021-12-27 07:23 UTC, jacopen approved these changes

2021-12-27 07:24 UTC, merged