全登壇者向け通知で CFP 不採択者を除外する
cloudnativedaysjp/dreamkast pull request #1081
Opened 2022-01-08 10:32 UTC by oshiro3

# 1041

2022-01-08 10:46 UTC, showks-containerdaysjp commented
Review app

https://dreamkast-dk-1081.dev.cloudnativedays.jp

2022-01-11 11:11 UTC, takaishi commented on db/schema.rb
> +    t.boolean "to_all", default: false
Booleanのカラムを用意するのではなく、enumで扱えるようにした方がいいかなと思いました。このPRだと「採択された人」と「全員」の2パターンだけど、アナウンス対象としては「採択されなかった人」や「任意の人」もありえるので。

2022-01-16 04:30 UTC, oshiro3 commented on db/schema.rb
> +    t.boolean "to_all", default: false
enum で定義するように修正しました。

2022-01-16 05:57 UTC, takaishi requested changes
そういえば、CFP採択者のみに通知するスピーカーアナウンスを作成・公開した後にプロポーザルの採択・非採択がシステム上変わりうるのですが、そういう場合の想定って何かしていますか？

2022-01-16 05:57 UTC, takaishi commented on app/models/speaker.rb
> +  def proposal_accepted?
[IMO] メソッド名提案:

```suggestion
  def has_accepted_proposal?
```

2022-01-16 05:57 UTC, takaishi commented on app/helpers/speaker_announcements_helper.rb
> +  def is_to_all_announcements?(speakers)
[IMO] helperに定義するよりはspeaker_announcements_controllerに定義した方がいいかもと思いました。
view内の一カ所でしか使われてないので。

2022-01-16 05:57 UTC, takaishi commented on app/views/admin/speaker_announcements/_form.html.erb
> +        <%= form.label :receiver, 'CFP採択に関わらず通知', value: @speaker_announcement.receiver %>
ここで何も選択せずに登録ボタンを押すとエラーになりました。

```
'all' is not a valid receiver
```

2022-01-16 05:57 UTC, takaishi commented on app/views/admin/speaker_announcements/_form.html.erb
> +        <%= form.label :receiver, 'CFP採択者にのみ通知', value: @speaker_announcement.receiver %>
こちらを選択しても、スピーカー全員にリレーションが作られているようです。

2022-01-23 10:42 UTC, oshiro3 commented on app/models/speaker.rb
> +  def proposal_accepted?
suggestion 通りの修正を実施しました。

2022-01-23 10:43 UTC, oshiro3 commented on app/helpers/speaker_announcements_helper.rb
> +  def is_to_all_announcements?(speakers)
既に helper_method でコントーローラ内にいくつか定義されているのを忘れていました。
修正しました。

2022-01-23 10:44 UTC, oshiro3 commented on app/views/admin/speaker_announcements/_form.html.erb
> +        <%= form.label :receiver, 'CFP採択に関わらず通知', value: @speaker_announcement.receiver %>
hidden_filed に入れていた値の修正漏れがありました。
修正しました。

2022-01-23 11:06 UTC, oshiro3 commented on app/views/admin/speaker_announcements/_form.html.erb
> +        <%= form.label :receiver, 'CFP採択者にのみ通知', value: @speaker_announcement.receiver %>
> CFP採択者のみに通知するスピーカーアナウンスを作成・公開した後にプロポーザルの採択・非採択がシステム上変わりうるのですが、そういう場合の想定って何かしていますか？

アナウンス作成時のリレーションの作成では送信対象に関わらず全員分のリレーションを作成するようにしています。
その上で、取得時にプロポーザルの採択が０のスピーカーの場合は `accepted_only` のアナウンスを取得しないようにしています。
一部上記のロジックの実装に誤りがあったので [47717c3b80c5b244d49b33c626571b4bfdfcad4c](https://github.com/cloudnativedaysjp/dreamkast/pull/1081/commits/47717c3b80c5b244d49b33c626571b4bfdfcad4c) のコミットで修正を行っています。

2022-01-23 11:08 UTC, oshiro3 commented on app/views/admin/speaker_announcements/_form.html.erb
> +        <%= form.label :receiver, 'CFP採択者にのみ通知', value: @speaker_announcement.receiver %>
スピーカーの数はそこまで大きくないため、全員分を作成することはそれほど大きな負荷にはならないだろうと考えました。

2022-01-24 10:07 UTC, takaishi commented on app/helpers/speaker_announcements_helper.rb
> +  def is_to_all_announcements?(speakers)
[nits] helper_methodにする場合、引数で `@speakers` を渡さずにメソッドないで直接 `@speakers` を参照してもいいかなと思いました

2022-01-24 10:17 UTC, takaishi commented on app/views/admin/speaker_announcements/_form.html.erb
> +        <%= form.label :receiver, 'CFP採択者にのみ通知', value: @speaker_announcement.receiver %>
なるほど。Speakerが見てもいいSpeakerAnnounceにのみリレーションを貼る方が安全じゃないかと個人的には思いますが、テストでカバーされていればこれでもいいかな…
Request SpecでもSpeakerAnnouceの見える・見えないのテストを書いておいてほしいです 🙏

2022-02-05 01:38 UTC, oshiro3 commented on app/views/admin/speaker_announcements/_form.html.erb
> +        <%= form.label :receiver, 'CFP採択者にのみ通知', value: @speaker_announcement.receiver %>
予めリレーションを作るとプロポーザルの結果変更などの操作についてリレーションの変更が必要になってしまうので、一旦このようにしました。
けど、想定していた以上にこの機能の複雑性が高いことに気が付いたので正直悩んではいます。
Request に Spec を作成しました。

2022-02-05 01:39 UTC, oshiro3 commented on app/helpers/speaker_announcements_helper.rb
> +  def is_to_all_announcements?(speakers)
直接参照する方が見通しが良くなると思ったので、こちらも修正しました。

2022-02-05 01:56 UTC, takaishi commented on spec/requests/speaker_dashboard_spec.rb
> +            allow_any_instance_of(Speaker).to(receive(:has_accepted_proposal?).and_return(true))
ここ、スタブせずに実データを使って採択プロポーザルを持っているかどうか見てもらってもいいですか？そこのロジックも含めてテストしたいです

2022-02-05 03:43 UTC, oshiro3 commented on spec/requests/speaker_dashboard_spec.rb
> +            allow_any_instance_of(Speaker).to(receive(:has_accepted_proposal?).and_return(true))
了解です。
修正しました。

2022-02-05 03:45 UTC, oshiro3 commented on spec/requests/speaker_dashboard_spec.rb
> +            allow_any_instance_of(Speaker).to(receive(:has_accepted_proposal?).and_return(true))
この `has_accepted_proposal?` メソッドに関する詳細はモデルのテストで行っています。

2022-02-05 06:43 UTC, takaishi approved these changes

2022-02-06 06:01 UTC, merged