MediaLive ChannelからMediaPackage Channelにストリーミングする
cloudnativedaysjp/dreamkast pull request #1096
Opened 2022-01-15 07:09 UTC by takaishi

* このPRは配信・録画アーキテクチャ変更の一環で、録画アーキテクチャ変更の第1弾です。
* 録画をMediaPackageで行うように変更するので、そのためのリソース作成や設定変更
  * MediaPackage Channelリソースを作成可能にする
  * MediaLiveからIVSとMediaPackageの両方にストリーミングするように変更する
* このPRではアーカイブ動画の切り出し機能は実装しません（別PRでやる）

https://github.com/cloudnativedaysjp/dreamkast/issues/989

2022-01-15 07:15 UTC, showks-containerdaysjp commented
Review app

https://dreamkast-dk-1096.dev.cloudnativedays.jp

2022-01-23 06:22 UTC, jacopen requested changes

2022-01-23 06:22 UTC, jacopen commented on app/helpers/media_package_helper.rb
> +    end
メモ:
今回やる必要はないんだけど、この『アクセスキーとシークレットがあったらそれを使って、無かったら使わない(insntance profileを返す)』というパターン、Dk全体の至る所にあるので、どこかで共通化したいなと思った

2022-01-23 06:22 UTC, jacopen commented on app/models/live_stream_media_live.rb
> +          video_description('video_480p30', 480, 854, 1500000, 100),
メモ: videoとaudioのビットレート値、あとでチューニングする(5Mbpsはカンファレンス動画としてはデカすぎるかもと思った)

2022-01-23 06:49 UTC, takaishi commented on db/schema.rb
> +    t.string "channel_id"
https://github.com/cloudnativedaysjp/dreamkast/pull/1096/commits/afa9a34aa5e9acb894b20e83170b3ab38c8f8a32

2022-01-23 07:03 UTC, jacopen approved these changes

2022-01-23 07:03 UTC, merged