Record archive video
cloudnativedaysjp/dreamkast pull request #1100
Opened 2022-01-23 08:11 UTC by takaishi

2022-01-23 08:22 UTC, showks-containerdaysjp commented
Review app

https://dreamkast-dk-1100.dev.cloudnativedays.jp

2022-01-23 14:58 UTC, showks-containerdaysjp commented
Review app

https://dreamkast-dk-1100.dev.cloudnativedays.jp

2022-01-26 08:41 UTC, jacopen requested changes

2022-01-26 08:41 UTC, jacopen commented on lib/tasks/polling_harvest_job_and_update_video.rake
> +  def cloudfront_domain_name(bucket_name)
これと一緒にEnvHelperにもっていけないかな
https://github.com/cloudnativedaysjp/dreamkast/blob/0d63ef8b7711241a21e2c8d32467ae5f962b753c/app/models/live_stream_media_live.rb#L191-L200

2022-01-26 08:41 UTC, jacopen commented on lib/tasks/polling_harvest_job_and_update_video.rake
> +      r = client.describe_harvest_job(id: harvest_job.job_id)
これはmodelにある jobメソッドを呼ぶ形でいけないかな？
https://github.com/cloudnativedaysjp/dreamkast/pull/1100/files#diff-81622305f2011e35ae02c5857a0566f4b9dc2ffbc029aa01342fc8ae14ad6d12R34-R36

あと変数 `r` が何を意味する略なのかちょっと分かりづらいなとおもった

2022-01-26 09:50 UTC, takaishi commented on lib/tasks/polling_harvest_job_and_update_video.rake
> +  def cloudfront_domain_name(bucket_name)
ここで使ってるcloudfront_domain_nameはバケット名からドメイン名を取得するもので、ここ以外だと今のところ使わないからまだこの位置でいいかなー

2022-01-26 10:03 UTC, jacopen commented on lib/tasks/polling_harvest_job_and_update_video.rake
> +  def cloudfront_domain_name(bucket_name)
OK

2022-01-26 10:22 UTC, jacopen approved these changes

2022-01-26 10:22 UTC, merged