Add exporter
cloudnativedaysjp/dreamkast pull request #1127
Opened 2022-02-09 01:15 UTC by mhoshi-vm

Prometheus ExporterをDreamkastに追加。

# How this was tested.

以下のようなデータを用意。

`Chat_Messages`
```
id,body,children_count,room_type,conference_id,parent_id,profile_id,room_id,speaker_id
1,aaaa,0,0,3,,,,201
2,BBBBBBB,0,0,3,,,,201
3,CC,0,0,3,,,,202
4,CC,0,0,4,,,,301
5,CC,0,0,4,,,,301
```

`Viewer_Count`
```
id,count,stream_type,conference_id,talk_id,track_id
1,10,hoge,3,201,1
2,20,hoge,3,202,3
3,150,hoge,4,401,1
4,200,hoge,5,502,2
```

これで `curl 0.0.0.0:3000/metrics` で実行した結果いかに

```
# TYPE dreamkast_viewer_count gauge
# HELP dreamkast_viewer_count Count dreamkast viewer number
dreamkast_viewer_count{talk_id="201",track_id="1",conference_id="3"} 10.0
dreamkast_viewer_count{talk_id="202",track_id="3",conference_id="3"} 20.0
dreamkast_viewer_count{talk_id="401",track_id="1",conference_id="4"} 150.0
dreamkast_viewer_count{talk_id="502",track_id="2",conference_id="5"} 200.0
# TYPE dreamkast_chat_count gauge
# HELP dreamkast_chat_count Count dreamkast chat number
dreamkast_chat_count{conference_id="3",talk_id="201"} 2.0
dreamkast_chat_count{conference_id="3",talk_id="202"} 1.0
dreamkast_chat_count{conference_id="4",talk_id="301"} 2.0
```

2022-02-09 01:16 UTC, mhoshi-vm commented
Specをつくったほうがいいですかね？その場合、InitializerのSpecはどこのディレクトリーに配置します？

2022-02-09 01:18 UTC, showks-containerdaysjp commented
Review app

https://dreamkast-dk-1127.dev.cloudnativedays.jp

2022-02-09 13:26 UTC, jacopen requested changes

2022-02-09 13:26 UTC, jacopen commented on config/initializers/prometheus.rb
> +        vcs = ViewerCount.all
allだと過去のイベントのものも混じっちゃいますが、表示側でコントロールする予定ですかね？

2022-02-09 13:26 UTC, jacopen commented on config/initializers/prometheus.rb
> +        chat_counts = ChatMessage.all.select(
これも同様に、過去イベントの扱いをどうするか、、、

2022-02-09 13:26 UTC, jacopen commented on config/initializers/prometheus.rb
> +            :conference_id, :speaker_id, ChatMessage.arel_table[:speaker_id].count.as('count')
これスピーカー単位のカウントになってますが、意図はあっていますか？
セッション単位でカウントならイメージ湧くのですが、スピーカー単位だとちょっとイメージが湧かないです(チャット書かないスピーカーが多いので)

2022-02-09 13:26 UTC, jacopen commented on config/initializers/prometheus.rb
> +      "#{metrics_prefix}_viewer_count".to_sym,
これが定数なのは違和感ありです。変数かなと

2022-02-09 13:26 UTC, jacopen commented on config/initializers/prometheus.rb
> +    CHAT_COUNT = Prometheus::Client::Gauge.new(
同上

2022-02-09 13:29 UTC, mhoshi-vm commented on config/initializers/prometheus.rb
> +        vcs = ViewerCount.all
それしかないかな、とおもっていました。
/metricsに今のところパラメーターなどを受け付けられるようになっていないので、Grafana側で表示コントロールかと思っています。

2022-02-09 13:29 UTC, mhoshi-vm commented on config/initializers/prometheus.rb
> +        chat_counts = ChatMessage.all.select(
同上。

2022-02-09 13:30 UTC, mhoshi-vm commented on config/initializers/prometheus.rb
> +            :conference_id, :speaker_id, ChatMessage.arel_table[:speaker_id].count.as('count')
ChatMessageのスキーマがよく理解できないのですが、どうやって、各セッションに紐づけているのですか？
値としては、speaker_idしかなく、ここから強引にセッションを紐づけているのかとおもっていました。

2022-02-09 13:43 UTC, jacopen commented on config/initializers/prometheus.rb
> +            :conference_id, :speaker_id, ChatMessage.arel_table[:speaker_id].count.as('count')
room_idがtalk_idと一致すると考えて貰えればよいです。
talk_idという名前じゃない理由は、必ずしもtalkと結びつかないケースがある(例えばイベント開始前など) のでこういう名前になってます。なので、意図したところがセッション単位で纏めたいというのならば、そっちでcountする必要ありです

2022-02-09 13:48 UTC, mhoshi-vm commented on config/initializers/prometheus.rb
> +            :conference_id, :speaker_id, ChatMessage.arel_table[:speaker_id].count.as('count')
なるほど！理解しました。

2022-02-09 14:03 UTC, jacopen requested changes

2022-02-09 14:03 UTC, jacopen commented on config/initializers/prometheus.rb
> +        vcs = ViewerCount.all
当日分だけ持ってくるというロジックは後から入れるとすると

```
Talk.accepted.each do |talk|
  Prometheus::Controller::viewer_count.set(
    ViewerCount.where(talk_id: talk.id).last.count,
    labels: { talk_id: talk.talk_id, track_id: talk.track_id, conference_id: talk.conference_id }
  )
end
```

みたいな感じですかね(実コードで確認できてないですが)

2022-02-10 14:37 UTC, mhoshi-vm commented on config/initializers/prometheus.rb
> +        vcs = ViewerCount.all
これでどうでしょう？
```
        accepted_talks = Talk.accepted.pluck(:id)


        vcs = ViewerCount.select(
          [
            :conference_id, :track_id, :talk_id, ViewerCount.arel_table[:count].maximum.as('count')
          ]
        ).where(talk_id: accepted_talks).group(:conference_id, :track_id, :talk_id)

        vcs.each do |vc|
          Prometheus::Controller::VIEWER_COUNT.set(
            vc.count,
            labels: { talk_id: vc.talk_id, track_id: vc.track_id, conference_id: vc.conference_id }
          )
        end
```

2022-02-10 14:38 UTC, mhoshi-vm commented on config/initializers/prometheus.rb
> +      "#{metrics_prefix}_viewer_count".to_sym,
ここなのですが、Ruby基本的な勘違いしているかもですが、定数化しないとcalculate_viewer_countやcalculate_chat_countから呼び出せなかったです。何か勘違いしているのであれば再挑戦します。

2022-02-10 14:38 UTC, mhoshi-vm commented on config/initializers/prometheus.rb
> +    CHAT_COUNT = Prometheus::Client::Gauge.new(
同上。

2022-02-10 14:42 UTC, mhoshi-vm commented
こんなデータで

ViewCount(@jacopen のコメントにあるよう、重複talk_idを考慮)
```
id,count,stream_type,conference_id,talk_id,track_id
1,10,hoge,3,201,1
2,20,hoge,3,202,3
3,150,hoge,4,401,1
4,200,hoge,5,502,2
5,200,hoge,5,301,5
6,100,hoge,5,301,5
7,200,hoge,5,341,2
8,150,hoge,5,301,5
```
ChatMessages
```
id,body,children_count,room_type,conference_id,parent_id,profile_id,room_id,speaker_id
1,aaaa,0,0,3,,,201,201
2,BBBBBBB,0,0,3,,,201,201
3,CC,0,0,3,,,202,202
4,CC,0,0,4,,,301,301
5,CC,0,0,4,,,301,301
```

でメトリクスの結果

```
% curl 0.0.0.0:3000/metrics
# TYPE dreamkast_viewer_count gauge
# HELP dreamkast_viewer_count Count dreamkast viewer number
dreamkast_viewer_count{talk_id="301",track_id="5",conference_id="5"} 200.0
dreamkast_viewer_count{talk_id="341",track_id="2",conference_id="5"} 200.0
# TYPE dreamkast_chat_count gauge
# HELP dreamkast_chat_count Count dreamkast chat number
dreamkast_chat_count{conference_id="3",talk_id="201"} 2.0
dreamkast_chat_count{conference_id="3",talk_id="202"} 1.0
dreamkast_chat_count{conference_id="4",talk_id="301"} 2.0
```

2022-02-10 15:09 UTC, jacopen commented on config/initializers/prometheus.rb
> +      "#{metrics_prefix}_viewer_count".to_sym,
Module定数として宣言してるからそうですね。
今回のこれがそもそもModuleである必要性があまりないので、この問題になってると思います

2022-02-10 15:35 UTC, jacopen requested changes

2022-02-10 15:35 UTC, jacopen commented on config/initializers/prometheus.rb
> +      "#{metrics_prefix}_viewer_count".to_sym,
Module定数を無理矢理宣言してそれを外から呼んでいるから変な感じになっていますね。

そもそもこのままでは外部から活用することもままならないので、このController moduleを無くしてシンプルにexporterに持って行くか、あるいはちゃんとModuleとしてメソッドを定義して外部から使えるようにしないとダメかなと

2022-02-10 15:41 UTC, jacopen commented
@mhoshi-vm 改めて全体見直したんですが、やっぱり全体的にmoduleにする必要性がなさそうです。今回の用途だとCustomExporterを作る必要もあまりなくて、むしろModelにGaugeの登録を実装していくほうがRailsとしてスッキリくるように思います。

2022-02-10 15:54 UTC, mhoshi-vm commented on config/initializers/prometheus.rb
> +        vcs = ViewerCount.all
@jacopen 
どういつtalk_idの中で、id値の最大値 = 最新のViewer_countであっています？Yesの場合、最新のコミットをみていただけますか？

2022-02-11 03:07 UTC, oshiro3 commented on config/initializers/prometheus.rb
> +    class CustomExporter < Prometheus::Middleware::Exporter
プロトタイプ的な温度感であれば問題ないと思いますが今後 o11y team で exporter を追加したいとかがありそうなのであれば、トップにいる Exporter は `respond_with` だけにして `calculate_xxx` は mix-in や DI して別にそれ専用の定義/実装するなどが良さそうかと思いました。
後 nits ですがクラス名は `DreamkastExporter` みたいな名前の方が役割が明確に感じます。

2022-02-11 12:08 UTC, jacopen commented
#1140 のほうでいこうかなと思うので、こちらは閉じますねー

2022-02-11 12:08 UTC, closed without merging