Image cropping
cloudnativedaysjp/dreamkast pull request #1178
Opened 2022-02-23 12:18 UTC by oshiro3

2022-02-23 12:19 UTC, showks-containerdaysjp commented
Review app

https://dreamkast-dk-1178.dev.cloudnativedays.jp

2022-02-27 14:43 UTC, jacopen commented
みます！

2022-02-28 12:02 UTC, oshiro3 commented
https://github.com/cloudnativedaysjp/dreamkast/pull/1178/commits/5a5ebe96cbdf26de505c2df5b4c8fe9ecd7efa81  が原因で cropbox.js が読み込まれなくなっちゃってますね...

2022-02-28 13:23 UTC, jacopen commented
おおーすごい
<img width="896" alt="image" src="https://user-images.githubusercontent.com/79102/155990498-97feff30-50af-40b3-97d8-cfe4b93d65f1.png">

2022-02-28 13:28 UTC, jacopen commented
スピーカーダッシュボードでは良い感じにクロップされているけど、
![image](https://user-images.githubusercontent.com/79102/155990722-64983faf-3ca5-4e7a-936f-b2a6b2b88215.png)

セッション詳細のほうはオリジナルが使われてしまっている
![image](https://user-images.githubusercontent.com/79102/155990787-bc3862ba-912d-4765-bf03-a6e115a41318.png)

app/views/talks/partial_show/_col_speaker_avatar.html.erb
と
app/views/talks/_show_modal.html.erb

にも修正が必要ですね。

2022-02-28 13:43 UTC, jacopen commented
既に登録済みのスピーカーが編集する際は問題無いんですが、新たなユーザーがスピーカー登録する際にクロップ画面が出てこないです

<img width="604" alt="image" src="https://user-images.githubusercontent.com/79102/155991799-418eef40-0b78-4c1f-9e99-b72665d78e13.png">

2022-02-28 13:45 UTC, jacopen requested changes
機能としては最高です！！

いくつか追加修正が必要そうなのでそちらを対応お願いします！

2022-02-28 13:45 UTC, jacopen commented on app/views/event/cndt2021_show.html.erb
> +                    <%= image_tag speaker.avatar_or_dummy_url(:medium), :size => '100x100', class: "rounded-circle" %><br/>
修正先ファイルがcndt2021になっているのでo11y側に修正するようにお願いします！

2022-02-28 13:45 UTC, jacopen commented on app/javascript/packs/cropbox.js
> +$(function () {
徐々にjQuery依存を外していきたいので、jQuery使わない形にしてもらえると助かります！

```
document.addEventListener('DOMContentLoaded', function() {
    something()
});
```

2022-03-01 09:55 UTC, takaishi commented
画像変換にImagemagickを使っていますが、以下の点からlibvipsなど別のライブラリを使えないでしょうか？

1. 脆弱性が多く、安全に使うためにpolicy.xmlでいろいろ設定する必要があり手間である
2. Active Storageは7.0以降で新規アプリではlibvipsをimagemagickのかわりに使うように変わっている。libvipsはパフォーマンスにも優れている。

2022-03-01 13:23 UTC, oshiro3 commented on app/views/event/cndt2021_show.html.erb
> +                    <%= image_tag speaker.avatar_or_dummy_url(:medium), :size => '100x100', class: "rounded-circle" %><br/>
こちら o11y2022 に修正しました。

2022-03-01 13:23 UTC, oshiro3 commented on app/javascript/packs/cropbox.js
> +$(function () {
eventListner を使用するように変更しました。

2022-03-01 13:24 UTC, oshiro3 commented
> 既に登録済みのスピーカーが編集する際は問題無いんですが、新たなユーザーがスピーカー登録する際にクロップ画面が出てこないです
スピーカーが nil の場合に DOM が生成されていなかったので、その点を修正しました。

2022-03-01 13:25 UTC, oshiro3 commented
Imagemagick の脆弱性等は知りませんでした。
ご指摘ありがとうございます。
`libvips` を使用するように変更しました。

2022-03-01 13:31 UTC, oshiro3 commented
GHAにも変更が必要そうなので修正します

2022-03-01 15:26 UTC, oshiro3 commented
local では特に影響していなかったのですが、どうやら画像処理が上手く行っていないようなので対応します
```
E, [2022-03-01T15:22:42.566707 #13] ERROR -- : [85e67899-3b44-4b03-90d2-7681c7df7db9] [ActiveJob] [PromoteJob] [601dbe60-c45c-44c7-9524-bb1a13168f8d] Error performing PromoteJob (Job ID: 601dbe60-c45c-44c7-9524-bb1a13168f8d) from AmazonSqs(default) in 23.41ms: Vips::Error (VipsForeignLoad: "/tmp/shrine20220301-13-rv9nau.png" is not a known file format
VipsForeignLoad: "/tmp/shrine20220301-13-rv9nau.png" is not a known file format
):
/usr/local/bundle/gems/ruby-vips-2.1.4/lib/vips/image.rb:281:in `new_from_file'
```

2022-03-02 11:42 UTC, jacopen approved these changes
Review appで動作確認しました、問題なさそう！

2022-03-06 08:44 UTC, takaishi approved these changes

2022-03-06 08:44 UTC, merged