add cm sponsor
cloudnativedaysjp/dreamkast pull request #1182
Opened 2022-02-28 09:41 UTC by takaishi

https://cloudnativedays.slack.com/archives/C015CN1PQ06/p1646035683280579

2022-02-28 09:47 UTC, showks-containerdaysjp commented
Review app

https://dreamkast-dk-1182.dev.cloudnativedays.jp

2022-03-01 10:26 UTC, jacopen requested changes
ロゴデータがないので死んでるー

2022-03-01 10:27 UTC, jacopen commented
@takaishi 
このロゴ.png、特にトリミングせず使えそうなのでリネームしてコミットしてちょ
https://drive.google.com/drive/folders/1wqFznJ51AhvAp2PngU6OhiNvO_P_eUUA

2022-03-01 13:00 UTC, jacopen commented
早めにリリースした方が良さそうなので自分の方でいれましたー

2022-03-01 14:32 UTC, jacopen commented
OK
![image](https://user-images.githubusercontent.com/79102/156188007-c9ca2c7e-d5bd-4bdf-b178-d29a30351322.png)

2022-03-01 14:32 UTC, merged

2022-03-02 01:32 UTC, takaishi commented
あざす