Update Sentry and some settings
cloudnativedaysjp/dreamkast pull request #1208
Opened 2022-04-05 04:01 UTC by inductor

- redis_logger が使えるようになったっぽいので入れてみる

リリース管理ができるようになったらしい。

![image](https://user-images.githubusercontent.com/20236173/161676330-511efcd5-e694-40d8-8418-8518f2263ea5.png)

今は入れてないが下記コードみたいなのを入れるか、Sentry側でリポジトリの連携を入れるとこんな感じでセッション数のトラックもできるようになるらしい。

```ruby
Sentry.init do |config|
  config.release = 'release-foo-v1'
end
```

2022-04-05 04:03 UTC, showks-containerdaysjp commented
Review app

https://dreamkast-dk-1208.dev.cloudnativedays.jp

2022-04-05 04:14 UTC, inductor commented on config/initializers/sentry.rb
> +  end
https://docs.sentry.io/product/performance/ を有効にするための設定

2022-04-05 04:30 UTC, jacopen requested changes
CIしんでますー

2022-04-05 04:51 UTC, inductor commented
CIなおった

2022-04-06 08:48 UTC, jacopen approved these changes

2022-04-06 08:48 UTC, merged