Adjust profile form
cloudnativedaysjp/dreamkast pull request #1251
Opened 2022-06-17 10:32 UTC by takaishi

https://github.com/cloudnativedaysjp/dreamkast/issues/1228

2022-06-17 10:36 UTC, showks-containerdaysjp commented
Review app

https://dreamkast-dk-1251.dev.cloudnativedays.jp

2022-06-19 07:34 UTC, jacopen requested changes
```
I, [2022-06-19T07:31:34.616058 #13]  INFO -- : [fa335d39-16eb-4471-b9eb-07a4fe6c690e] Started POST "/cnsec2022/profiles" for 10.100.74.206 at 2022-06-19 07:31:34 +0000
I, [2022-06-19T07:31:34.618015 #13]  INFO -- : [fa335d39-16eb-4471-b9eb-07a4fe6c690e] Processing by ProfilesController#create as HTML
 Parameters: {"authenticity_token"=>"[FILTERED]", "profile"=>{"last_name"=>"草間", "first_name"=>"一人", "last_name_kana"=>"クサマ", "first_name_kana"=>"カズト", "industry_id"=>"1", "occupation"=>"テスト", "company_name_prefix_id"=>"1", "company_name"=>"テスト", "company_name_suffix_id"=>"", "company_email"=>"jacopen@gmail.com", "company_postal_code"=>"108-0023", "company_address_level1_id"=>"13", "company_address_level2"=>"港区", "company_address_line1"=>"芝浦2-3-28", "company_address_line2"=>"sdfdsfs", "company_tel"=>"+81-80-3700-3818", "department"=>"テスト", "position"=>"テスト"}, "commit"=>"個人情報保護方針に同意して参加登録", "event"=>"cnsec2022"}
E, [2022-06-19T07:31:34.625365 #13] ERROR -- : [fa335d39-16eb-4471-b9eb-07a4fe6c690e] Rendering 500 with exception: unknown attribute 'company_address_level1_id' for Profile.

          raise UnknownAttributeError.new(self, k.to_s)
          ^^^^^
E, [2022-06-19T07:31:34.625764 #13] ERROR -- : [fa335d39-16eb-4471-b9eb-07a4fe6c690e] /usr/local/bundle/gems/activemodel-7.0.2.4/lib/active_model/attribute_assignment.rb:51:in `_assign_attribute'
```

このエラーが出てProfile登録できずー

2022-06-19 07:39 UTC, jacopen requested changes

2022-06-19 07:39 UTC, jacopen commented on app/views/profiles/_form.html.erb
> +    <%= form.text_field :company_tel, required: true, class: "form-control", placeholder: "0300000000 or 030-000-0000", pattern: "[\\d+-]*" %>
ハイフン入れても除去されるからOKという意味合いでこのプレースホルダなんだと思うけど、入力項目としてはハイフン無しで入れて貰うようにしたほうがユーザー側としても混乱がなくていいかなと。

もしコピペでハイフンが入ったとしても裏でこっそり直してくれる、くらいの感覚

```suggestion
    <%= form.text_field :company_tel, required: true, class: "form-control", placeholder: "0311112222", pattern: "[\\d+-]*" %>
```

2022-06-19 07:39 UTC, jacopen commented on app/views/profiles/_form.html.erb
> +    <%= form.text_field :company_postal_code, required: true, class: "form-control", minlength: "7", maxlength: "8", pattern: "(\\d{7}|\\d{3}-\\d{4})", placeholder: "1000001 or 100-0001", autocomplet
電話番号と同じ
```suggestion
    <%= form.text_field :company_postal_code, required: true, class: "form-control", minlength: "7", maxlength: "8", pattern: "(\\d{7}|\\d{3}-\\d{4})", placeholder: "1000001", autocomplete: "postal-code" %>
```

2022-06-20 09:29 UTC, takaishi commented on app/views/profiles/_form.html.erb
> +    <%= form.text_field :company_tel, required: true, class: "form-control", placeholder: "0300000000 or 030-000-0000", pattern: "[\\d+-]*" %>
うーん、ユーザーに直す手間をかけさせたくないんだよなあ。

2022-06-20 10:02 UTC, dreamkast-cloudnativedays commented
Review app

https://dreamkast-dk-1251.dev.cloudnativedays.jp

2022-06-20 10:15 UTC, dreamkast-cloudnativedays commented
Review app

https://dreamkast-dk-1251.dev.cloudnativedays.jp

2022-06-20 10:19 UTC, takaishi commented
> このエラーが出てProfile登録できずー

これはReviewAppを作り直して解消

2022-06-21 00:14 UTC, takaishi commented
都道府県用のフィールドにActiveHash使うの微妙かも？と思ってちょっと手を入れたいので一旦レビューリクエストは解除

2022-06-21 10:27 UTC, dreamkast-cloudnativedays commented
Review app

https://dreamkast-dk-1251.dev.cloudnativedays.jp

2022-06-25 02:09 UTC, dreamkast-cloudnativedays commented
Review app

https://dreamkast-dk-1251.dev.cloudnativedays.jp

2022-06-25 02:21 UTC, jacopen requested changes
新規登録のところはOKなんだけど、登録情報変更画面のフォームの横幅が狭いままなので、こっちも広くしてもらえれば！

それ以外は大丈夫そう

![image](https://user-images.githubusercontent.com/79102/175754584-7ce5ceb5-1b81-4ffd-82c5-fd7d29fbe36a.png)

2022-06-25 17:45 UTC, jacopen approved these changes

2022-06-25 17:46 UTC, merged