登壇者お知らせの公開時に通知されなかったため、メール送信処理を追加
cloudnativedaysjp/dreamkast pull request #1252
Opened 2022-06-18 10:24 UTC by oshiro3

#1199 

個人宛通知を公開で作成した場合と、非公開の個人宛通知を公開にした場合に通知するようにしました。
後者については `publish_changed?` と `publish == true` で判定しているため「非公開 -> 公開 -> 非公開 -> 公開」などの場合再度通知されてしまいますが、運用上発生しえないだろうと考えたのでこの P/R ではケアしていません。

2022-06-18 10:26 UTC, oshiro3 commented
> 後者については publish_changed? と publish == true で判定しているため「非公開 -> 公開 -> 非公開 -> 公開」などの場合再度通知されてしまいますが、運用上発生しえないだろうと考えたのでこの P/R ではケアしていません。

ケアが必要な場合「通知済みかどうか」を状態として保持する必要があるため `SpeakerAnnouncement` に属性としてDBに持たせるなどが妥当かなと思います。

2022-06-18 10:27 UTC, showks-containerdaysjp commented
Review app

https://dreamkast-dk-1252.dev.cloudnativedays.jp

2022-06-19 07:15 UTC, jacopen commented
ありがとうございます！

メール周りの運用は @nabemasat さんとも連携する必要があるので、実際どう運用するか火曜日の実行委員会のあとに話しますか > @nabemasat

2022-06-19 09:00 UTC, nabemasat commented
@jacopen @oshiro3 
了解です！

2022-06-21 10:39 UTC, jacopen requested changes
鍋島さんらと仕様について詰めましたー

■ 修正お願いしたい点:

たとえばお知らせ通知を間違ってしまった場合、間違った内容で送られてしまう＆それを修正した場合にもメールが飛んでしまう形になります。例えばZoomリンクの取り違えなど、大きめのミスが発生した場合にメールだと混乱が起きてしまう可能性も考えられました。

そこで、送る文面にはお知らせのボディを入れるのではなく

```
新しいお知らせが到着しました。

確認するには、イベントサイトのスピーカーダッシュボードをご確認ください
https://event.cloudnativedays.jp/cnsec2022
```

みたいな定型文にしてもらうことでリスクを減らせそうです。2回送られても大きな問題になりません。

■ 必ずしもこのPRで対応する必要はないが、実装規模がどのくらいになるか相談

現時点では個人向けのメッセージのみが通知対象になっています。ですが、出来れば全体配信、CFP採択者向け、非採択者向けメッセージも同じくメールが飛んでくれた方が嬉しいです。

実装規模が大きくなりそうであれば別PRに分けてもらっても構いません。それほど大きくなさそうなら一緒に入れるのも選択肢かなと思っています

2022-06-21 13:48 UTC, oshiro3 commented
ご指摘の点を受けまして下記修正を行いました。
- body を定型文に変更https://github.com/cloudnativedaysjp/dreamkast/blob/33f6552c1c88f224a4692c438876a7fc8cba8239/app/views/speaker_mailer/inform_speaker_announcement.text.erb#L1-L6 
- メールの送信条件について送信対象をすべてのメールに拡大

2022-06-25 02:04 UTC, dreamkast-cloudnativedays commented
Review app

https://dreamkast-dk-1252.dev.cloudnativedays.jp

2022-06-25 02:05 UTC, dreamkast-cloudnativedays commented
Review app

https://dreamkast-dk-1252.dev.cloudnativedays.jp

2022-06-25 17:46 UTC, jacopen approved these changes

2022-06-25 17:46 UTC, merged