remove seed talks don't have conference_day_id
cloudnativedaysjp/dreamkast pull request #1370
Opened 2022-07-29 09:57 UTC by takaishi

fix https://github.com/cloudnativedaysjp/dreamkast/issues/1348

2022-07-29 10:00 UTC, dreamkast-cloudnativedays commented
Review app

https://dreamkast-dk-1370.dev.cloudnativedays.jp

2022-07-29 11:15 UTC, jacopen requested changes
Review appsの初期シードの話だけでいうとこの修正でいいんだけど、StagingやProductionにもconference_day_idがNULLのものがあって、やっぱり死んじゃうとおもう。
![image](https://user-images.githubusercontent.com/79102/181747623-97dce4ba-64bf-4af1-bc03-d626c74652f2.png)

よく考えたらProposalが却下された場合Conference Dayを割り当てられることなく放置されるのは仕様上仕方ないなと。

なので、API側のほうでNULLであっても正しく出力されるように修正する方が良いともう

2022-07-29 23:44 UTC, takaishi commented
あー、rejectになるとnullになることがあるか。この方法だとだめだな。

2022-07-30 00:22 UTC, dreamkast-cloudnativedays commented
Review app

https://dreamkast-dk-1370.dev.cloudnativedays.jp

2022-07-30 03:30 UTC, closed without merging