Port swagger manifests from dreamkast-api-docs
cloudnativedaysjp/dreamkast pull request #1502
Opened 2022-09-21 10:54 UTC by hrk091

- dreamkast-api-docsの一式をdreamkast repoに移しました。
- dreamkast-api-docsに設定されていたgithub-action（image作成とdreamkast-infraのimage bump up）を移行しました
- axios-clientを生成し、dreamkast-uiに追加するstepを追加しました。

確認していただきたいポイントは、コードの中でコメントします。

2022-09-21 11:07 UTC, hrk091 reviewed
現状使っていなさそうな、build.sh、task-definition.json は dreamkast/schemasに移設せず、必要そうなファイルだけに絞りました。こちらもまずければ、コメントいただけると助かります

2022-09-21 11:07 UTC, hrk091 commented on .github/workflows/make-swagger-artifacts.yml
> +        uses: docker://openapitools/openapi-generator-cli:v5.3.1
dreamkast-ui側のclient-axiosのversionが5.3.1だったので、5.3.1にしてます。
https://github.com/cloudnativedaysjp/dreamkast-ui/blob/main/src/client-axios/.openapi-generator/VERSION

最新にした方が良ければ、コメントいただければ最新のものに置き換えます

2022-09-21 11:10 UTC, hrk091 commented
> 現在swagger.ymlのマスターはdreamkast-api-docs上にあるが、これをdreamkastに移動する。具体的には、dreamkast-api-docs上のswagger.ymlをdreamkastにコピーして差分が確実にない状態とする。

との指示だったので、dreamkast-api-docsからswagger.ymlを持ってきましたが、「conflictしている = dreamkast側で変更が入っている」状態なので、どちらを使うのが正しいのか教えてもらえると助かります。

2022-09-22 08:08 UTC, jacopen commented
爆速対応！すばらしい

2022-09-22 08:10 UTC, jacopen commented on .github/workflows/make-swagger-artifacts.yml
> +          # TODO remove --skip-validate-spec flag
将来的にはvalidate通るようにした方がいいと思います。ただ、まずは仕組みが動くところまで持って行くのが重要だと思いますので、今回はこれで入れちゃいましょう

2022-09-22 08:12 UTC, jacopen commented
> > 現在swagger.ymlのマスターはdreamkast-api-docs上にあるが、これをdreamkastに移動する。具体的には、dreamkast-api-docs上のswagger.ymlをdreamkastにコピーして差分が確実にない状態とする。
> 
> との指示だったので、dreamkast-api-docsからswagger.ymlを持ってきましたが、「conflictしている = dreamkast側で変更が入っている」状態なので、どちらを使うのが正しいのか教えてもらえると助かります。

@hrk091 こちらはdreamkastに入っているほうが正でお願いします！ dreamkast-api-docsのほうはメンテが行き届いておらず古い状態になっています。

2022-09-22 08:12 UTC, jacopen commented
swagger.yamlをdreamkast側を正にしてもらう以外は問題無いと思います。めっちゃ助かります 🙏

2022-09-22 08:13 UTC, jacopen requested changes
.

2022-09-22 11:07 UTC, hrk091 commented
@jacopen
latest/mainに対してrebaseしつつ、swagger.ymlに対する変更をdropしてdreamkastのswagger.ymlを使うようにしました。

2022-09-22 11:12 UTC, hrk091 commented on .github/workflows/make-swagger-artifacts.yml
> +          # TODO remove --skip-validate-spec flag
ありがとうございます、了解です。
issue作りました: https://github.com/cloudnativedaysjp/dreamkast/issues/1504

2022-09-23 01:22 UTC, takaishi reviewed
github actionsのshellcheck対応をお願いします〜

2022-09-23 02:12 UTC, hrk091 commented
@takaishi 
shellcheck対応しました。

> See if you can use ${variable//search/replace} instead

こちらが2件でていますが、sedでの置換がdreamkast-api-docsからそのままportingしてきた実績ある記述なので、このまま維持とさせてくださいー

2022-09-23 03:43 UTC, jacopen approved these changes

2022-09-23 03:43 UTC, merged