Add OIDC debugger
cloudnativedaysjp/dreamkast pull request #1522
Opened 2022-10-02 08:34 UTC by jacopen

2022-10-05 08:49 UTC, hrk091 commented on app/controllers/api/v1/debug_controller.rb
> +  include SecuredPublicApi
SecuredPublicApiを他のAPI endpointにも設定してUIと結合させた所、ちゃんとJWTで連携して動いていることが確認できました。ありがとうございます！

2022-10-05 08:49 UTC, hrk091 commented on app/controllers/api/v1/debug_controller.rb
> +  before_action :authenticate_request!, only: [:index]
1点確認させてください。
この実装で問題なく動くのですが、SecuredApiと併用することができず（session方式かJWTかどちらかを選択する形になる）、後方互換がない修正になっています。
これだとdk-ui側のAPI client修正と同時にデリバリしないと壊れてしまうため、それを避けたければ、dk側は移行中はsessionとJWTの両方をサポートする必要があります。

といいつつ、変更箇所がそこまで多くないのとdk・dk-uiともにデリバリのタイミングを我々でコントロールできることから、後方互換担保せずに突き進むのも全然ありだと思っています。今回はその作戦で行くと考えて良いでしょうか？

2022-10-05 14:27 UTC, jacopen commented on app/controllers/api/v1/debug_controller.rb
> +  before_action :authenticate_request!, only: [:index]
はい、突き進む作戦で良いと思います！

2022-10-05 15:26 UTC, hrk091 requested changes

2022-10-05 15:26 UTC, hrk091 commented on app/controllers/concerns/secured_public_api.rb
> +    if @current_user[:extra][:raw_info]['name'].present?
@jacopen 
current_userを使うAPIの検証（chat_message create）をやっていたところ、info配下のfieldが格納されていないことがわかりました。
で、よく考えると、このあたりの情報は標準のJWTのclaimからは取れないので、他の方法で別途取得する必要があります。。。
（Username/Password認証の場合は値が入っているかもですが、googleなどでSSOすると値が入らないです）
https://community.auth0.com/t/how-can-i-fetch-more-user-data-on-get-userinfo/73340

別の方法としては、
- auth0のmanagement APIを使う（backend側で、client credential flowでmanagement APIを叩く形になります）
- auth0 ruleを使って、custom claimとして追加する

などがあります。

参考までに、私が別件で同様の対応をしたときは、前者の方式で `GET /users-by-email` endpointを叩いて取得していました。
https://auth0.com/docs/manage-users/user-search/retrieve-users-with-get-users-by-email-endpoint

2022-10-05 16:09 UTC, hrk091 commented on app/controllers/concerns/secured_public_api.rb
> +    if @current_user[:extra][:raw_info]['name'].present?
auth0 ruleをチラ見してみたら、すでに結構使われてますし、users-by-email endpointも叩いているみたいですね。。。元々考慮されているのがちゃんと動いていない？

2022-10-06 00:52 UTC, hrk091 commented on app/controllers/concerns/secured_public_api.rb
> +    if @current_user[:extra][:raw_info]['name'].present?
`/users-by-email` を叩いているruleはありましたが、custom claimを足しているわけではなさそうでした。やはり対応が必要そうです

2022-10-06 01:49 UTC, jacopen commented on app/controllers/concerns/secured_public_api.rb
> +    if @current_user[:extra][:raw_info]['name'].present?
得られたid_tokenのclaim見てみると、必要な情報はだいたい入ってますね(Google認証)
![image](https://user-images.githubusercontent.com/79102/194194833-d2336101-cfc3-4c4a-bc71-da3b5b273f42.png)

info配下のfieldが格納されていないってうのがどこで起きているのかちょっと分からないですが、Auth0から情報が取れていないというわけではなさそう

2022-10-06 02:35 UTC, hrk091 commented on app/controllers/concerns/secured_public_api.rb
> +    if @current_user[:extra][:raw_info]['name'].present?
slackより転記

```
Hiroki Okui
あーなるほど。id_tokenを使う前提でbackendを作られてたってことですね。
id_tokenは同一ドメインの場合のsession tokenとして使うのはありなんですが、3rd partyからのリクエストのときはaccess_tokenを使うのが正しいという棲み分けになっています。今回はSPAとして分離しドメインも分けて、UI (client/RP)からbackend API(resource-server) に対してのアクセスなので、access_tokenを使うのがOAuth2/OIDCの正しい使い方になります。


jacopen
あ～～なるほど


Hiroki Okui
というのは建前で、ぶっちゃけていうと、上記想定なのでauth0-reactが提供しているライブラリがaccess_tokenしか渡してくれないからaccess_tokenを使わざるを得ない、というのが本音です。。

id_tokenを取る方法がわかったら、別にid_tokenでも良いと思います（ほぼ自ホストみたいなものなので） （編集済み） 


jacopen
:image_naruhodo:


Hiroki Okui
access_tokenだと、custom claimなしだとこの情報しかくれないので、追加しないといけないんですよね


jacopen
理解しました
追加してくれたruleによってaccess_tokenに情報が追加されるので、それを読むようにRails側をしゅしゅっと直せば良い感じですね


Hiroki Okui
さらにいうと、実はこのaccess_tokenにuserに関するcustom claimを付与するのは邪道で、userを識別できる情報は本来id_tokenしか持ってはいけないです。
なので、auth0 ruleを使うよりも、ticketにも書いた後者の「backend rails側でuserinfoをUIに返すAPIを具備する」の方が本当は正しいです


jacopen
:image_naruhodo:


Hiroki Okui
ただ、これやるとめんどくさい（しround tripの回数も増える）ので、access_token使いつつ最低限のuser識別情報を渡しちゃう、ぐらいであれば踏み外しても全然いいかなと思ってます


jacopen
:kanzenrikai:
```

2022-10-06 02:41 UTC, hrk091 commented on spec/rails_helper.rb
> +  [JSON.parse('{
access_token with custom claimを使う方式に変えたので、test fixtureを修正しました。
ついでに、dreamkast-ui reviewapps 用に用意したauth0 application向かいで取得したtoken payloadに変更してます（azpとかaudとか）

2022-10-06 02:41 UTC, hrk091 approved these changes
current_userを使うmutation含めて動作検証できたので、approveします

2022-10-06 04:46 UTC, jacopen commented
この修正は既存機能に対する影響が小さいのでマージしちゃいますー

2022-10-06 04:46 UTC, merged