add form for spnsors
cloudnativedaysjp/dreamkast pull request #1532
Opened 2022-10-06 10:46 UTC by takaishi

fix https://github.com/cloudnativedaysjp/dreamkast/issues/1496

<img width="709" alt="image" src="https://user-images.githubusercontent.com/107187/195105448-a61cb44a-bdb4-4384-a423-99c5ae3474a4.png">

![image](https://user-images.githubusercontent.com/107187/195821904-0502f586-9fe8-4df5-9c79-a79bf15b432c.png)

2022-10-06 13:12 UTC, takaishi commented
@jacopen とりあえず現状の要件でレビューよろ

2022-10-06 13:18 UTC, jacopen requested changes

2022-10-06 13:18 UTC, jacopen commented on app/views/profiles/sponsors/_ibm.html.erb
> +<h4 class="mt-3">協賛企業の日本アイ・ビー・エム株式会社からのご案内方法について</h4>
https://github.com/cloudnativedaysjp/dreamkast/issues/1496#issuecomment-1262109169
に文面の指定があるのでこれに変更おねしゃす

2022-10-06 13:18 UTC, jacopen commented on app/views/profiles/sponsors/_redhat.html.erb
> +  マーケティングに関する同意は、opt-out requestを送信することにより、いつでも取り消すことができます。また、該当の E メール内の、購読を中止するためのリンクをクリックすることで、マーケティングに関する E メールの受信を中止することができます。
鍋島さんの書いてくれている文面に、 `opt-out request` の部分のリンク先も載っているので、Aタグでリンク貼ってくださいな(IBMのほうも同様)
https://github.com/cloudnativedaysjp/dreamkast/issues/1496#issuecomment-1262109713

2022-10-07 11:33 UTC, takaishi commented on app/views/profiles/sponsors/_redhat.html.erb
> +  マーケティングに関する同意は、opt-out requestを送信することにより、いつでも取り消すことができます。また、該当の E メール内の、購読を中止するためのリンクをクリックすることで、マーケティングに関する E メールの受信を中止することができます。
RedHatについてはopt-out requestのURLは入手待ちでは？

2022-10-07 11:34 UTC, takaishi commented on app/views/profiles/sponsors/_ibm.html.erb
> +<h4 class="mt-3">協賛企業の日本アイ・ビー・エム株式会社からのご案内方法について</h4>
https://github.com/cloudnativedaysjp/dreamkast/pull/1532/commits/bb6dc91ca31f65d11aa1cbc03b04c7da765511b2

2022-10-11 02:13 UTC, nabemasat commented on app/views/profiles/sponsors/_redhat.html.erb
> +  マーケティングに関する同意は、opt-out requestを送信することにより、いつでも取り消すことができます。また、該当の E メール内の、購読を中止するためのリンクをクリックすることで、マーケティングに関する E メールの受信を中止することができます。
遅くなりすみません:bow:はい、RedHatについてはopt-out requestのURLは入手待ちです:bow:

2022-10-11 02:39 UTC, nabemasat commented on app/views/profiles/sponsors/_redhat.html.erb
> +  マーケティングに関する同意は、opt-out requestを送信することにより、いつでも取り消すことができます。また、該当の E メール内の、購読を中止するためのリンクをクリックすることで、マーケティングに関する E メールの受信を中止することができます。
スクリーンショット確認しました。営業チームから2点修正依頼が来ています。

> 処理に関する詳しい情報は、RED HATプライバシーステートメントをご覧ください。このフォームを送信することで、私は レッドハット プライバシーステートメントを読み、これを理解したものとします。

の一文が抜けているので、修正をお願いできますか。
https://github.com/cloudnativedaysjp/dreamkast/issues/1496#issuecomment-1262109713

また、リンクを埋めているワードを太字にする、色を変えるといった対応可能でしょうか。

2022-10-11 13:35 UTC, takaishi commented on app/views/profiles/sponsors/_redhat.html.erb
> +  マーケティングに関する同意は、opt-out requestを送信することにより、いつでも取り消すことができます。また、該当の E メール内の、購読を中止するためのリンクをクリックすることで、マーケティングに関する E メールの受信を中止することができます。
こちら対応済みです。スクリーンショットも更新しました。

2022-10-14 07:47 UTC, nabemasat commented on app/views/profiles/sponsors/_redhat.html.erb
> +  マーケティングに関する同意は、opt-out requestを送信することにより、いつでも取り消すことができます。また、該当の E メール内の、購読を中止するためのリンクをクリックすることで、マーケティングに関する E メールの受信を中止することができます。
@takaishi 
ありがとうございます！お待たせしました。両者確認取れました。
- IBM : 修正なしでOK
- レッドハット : opt-out requestのリンク
https://www.redhat.com/ja/email-preferences#unsubscribe_form

でお願いします！

2022-10-14 10:10 UTC, takaishi commented on app/views/profiles/sponsors/_redhat.html.erb
> +  マーケティングに関する同意は、opt-out requestを送信することにより、いつでも取り消すことができます。また、該当の E メール内の、購読を中止するためのリンクをクリックすることで、マーケティングに関する E メールの受信を中止することができます。
こちらは修正済み

2022-10-15 09:14 UTC, takaishi commented
URL更新したのでマージ

2022-10-15 09:15 UTC, merged