登録セッションのカレンダー同期機能
cloudnativedaysjp/dreamkast pull request #1550
Opened 2022-10-16 08:13 UTC by oshiro3

今回の実装スコープとしては
- 待機画面から「カレンダーに登録」ボタン押すと自分の登録してるカレンダーをダウンロードできる

です。

イベント全部や個人の登録からの選択、イベント自体の予定なども考えたのですが、ユーザー導線などを考えると複雑になるので一旦とりあえず一番使いそうな「個人のカレンダー全部」のみ実装してみました。

「個人の登録からの選択」は link_to のパラメータに check_box の値を入れる方法が簡単には見つからなかったのでそこがクリアできればすぐ入れられます。

ユニークコードのユーザー発行とか Profile 画面からの確認なども一旦省いてます。

本番に入れる場合は `util:add_unique_code_to_profile` タスクで環境変数 `EVENT_ABBR` に合わせたイベントの既存のProfile に unique_code を追加できます。

![image](https://user-images.githubusercontent.com/40717789/196025372-05edfa13-e1d2-4cc8-a0aa-2c58c73c88c9.png)

2022-10-16 08:19 UTC, jacopen requested changes

2022-10-16 08:19 UTC, jacopen commented on app/models/profile.rb
> +#  unique_code                   :string(255)
事前に連係できてなくてすみません！

こういうunique_code系は、今後ハイブリッドイベントにあたって他にも種類が増える可能性があります(例えばQRコードチェックインとか)
なので、区別が付くように `calendar_unique_code` とプレフィックスつけてもらっていいですか？

2022-10-16 08:40 UTC, oshiro3 commented on app/models/profile.rb
> +#  unique_code                   :string(255)
承知です！
`calendar_unique_code ` に修正しました。

2022-10-16 09:45 UTC, oshiro3 commented
review_app 初期化

2022-10-16 13:37 UTC, jacopen requested changes

2022-10-16 13:37 UTC, jacopen commented on app/models/talk.rb
> +      e.dtend       = Icalendar::Values::DateTime.new(end_time)
`start_time` と `end_time` はtime型なので、DateTime型として使うと2000年1月1日扱いになってしまう罠が。
![image](https://user-images.githubusercontent.com/79102/196038040-6b42bad5-c32d-4ea7-8e0b-b55e1595f6fb.png)

なので、 `conference_day.date` の日付をくっつけてあげる必要ありです

2022-10-16 13:37 UTC, jacopen commented on app/models/talk.rb
> +    cal
これは自分の環境要因なのか出力されているical側の問題なのかまだ絞り込めてないんですが、3セッション登録しているのにも関わらずカレンダーに載るのが1イベントしかないです

![image](https://user-images.githubusercontent.com/79102/196038418-2e067626-3d57-4eb7-88d3-567c6a860afd.png)
![image](https://user-images.githubusercontent.com/79102/196038423-37d365d3-22ba-4142-8907-15e8339ef582.png)
![image](https://user-images.githubusercontent.com/79102/196038428-e6389c27-1580-41d0-ac1a-0c2fe48c6637.png)

2022-10-16 13:46 UTC, takaishi commented on config/routes.rb
> +      get 'calendar', to: 'talks#calendar'
controllerはtalksではなくprofilesの方が適切かなと思います。

2022-10-16 13:46 UTC, takaishi commented on app/controllers/profiles/talks_controller.rb
> +  def calendar
今回のスコープの場合、聴講するセッションを変更した場合は再度カレンダーをダウンロードする必要がある、という理解で正しいですか？

2022-10-17 12:56 UTC, oshiro3 commented on app/models/talk.rb
> +    cal
自分の環境(windows10 + default のメーラー)では上手く登録できているように見えていますので、ちょっと再現できていないです。
代わりに日本語が文字化けしていたのでこちらの対応はいれます。
Gmail などでもインポート試してみます！

2022-10-17 12:57 UTC, oshiro3 commented on app/controllers/profiles/talks_controller.rb
> +  def calendar
その認識です。
個別の登録は早めに入れていきたいと思っています。

2022-10-22 12:59 UTC, oshiro3 commented on app/models/talk.rb
> +      e.dtend       = Icalendar::Values::DateTime.new(end_time)
修正しました。
イベントの日程が反映されていることを確認しました。

2022-10-22 13:01 UTC, oshiro3 commented on app/models/talk.rb
> +    cal
何故か過去のコードだと VCALENDAR が消えているっぽいですね。
 VCALENDAR 内にイベントが収まるように修正しました。
もうちょっと RFC で Multiple Event みたいなの定義しておいて欲しいなと思いました。

2022-10-22 13:02 UTC, oshiro3 commented on config/routes.rb
> +      get 'calendar', to: 'talks#calendar'
確かにその通りかと思います。
Profiles 下に修正しました。

2022-10-25 09:42 UTC, takaishi commented on app/controllers/profiles/talks_controller.rb
> +  def calendar
URLをカレンダーに登録したら後は定期的に自動更新されるような仕組みの方が使い勝手が良い気がするのだけど、難しそうですかね？もしくは、このPRの後続でやる感じでしょうか。

2022-11-01 13:16 UTC, oshiro3 commented on app/models/talk.rb
> +    event.description = abstract
トラックとURLを追加しました。
部屋情報ってタイムテーブル公開時点で既に決まっている & dk にありましたっけ？

2022-11-01 13:18 UTC, oshiro3 commented on app/controllers/profiles/talks_controller.rb
> +  def calendar
そうですね、現状 ics をダウンロードして手動で入れるのを前提にしていて、URLを登録して自動更新というのはちょっと未調査になるのですぐには難しいですが後続でつぶしていきたいと思います。

2022-11-02 09:30 UTC, takaishi commented on app/models/talk.rb
> +    event.description = abstract
決まっています！Trackからroomというrelationが生えていて、これが物理的な部屋情報です！

2022-11-03 08:28 UTC, oshiro3 commented on app/models/talk.rb
> +    event.description = abstract
なるほどです
部屋名を追加しました。

2022-11-03 09:38 UTC, takaishi approved these changes

2022-11-05 04:57 UTC, jacopen approved these changes

2022-11-05 04:58 UTC, merged