CNDT2022handson page
cloudnativedaysjp/dreamkast pull request #1556
Opened 2022-10-17 16:51 UTC by tkc66-buzz

2022-10-18 06:37 UTC, MasayaAoyama requested changes

2022-10-18 06:37 UTC, MasayaAoyama commented on app/views/contents/cndt2022_hands_on.html.erb
> +              午後 (14:00–):</b>
```suggestion
              午後 (14:00–18:00):</b>
```

2022-10-18 06:37 UTC, MasayaAoyama commented on app/views/contents/cndt2022_hands_on.html.erb
> +          <div class="handson-session">
このOracleのは不要です。市川さんのやつが２通目に出されたやつです

2022-10-18 06:37 UTC, MasayaAoyama commented on app/views/contents/cndt2022_hands_on.html.erb
> +            <h5 id="hs3"><strong>『OCI DevOps で体験する CI/CD パイプライン』 by 市川豊 / 仁井田拓也</strong></h5>
午前午後の中でのスポンサーの順番は申し込み順にしておきましょうか。
https://docs.google.com/spreadsheets/d/1qOn5K3xmeppa9R0FvLvy-XFE_5gW4BjWEy2cJIHmqYg/edit#gid=446104958

2022-10-18 06:37 UTC, MasayaAoyama commented on app/views/contents/cndt2022_hands_on.html.erb
> +        </div>
Kubernetes Upstream Trainingのも追加お願いします！
https://github.com/cloudnativedaysjp/cndt2022/issues/152#issuecomment-1280270589

参考
https://event.cloudnativedays.jp/cndt2021/hands-on#hs0

2022-10-18 15:20 UTC, tkc66-buzz commented on app/views/contents/cndt2022_hands_on.html.erb
> +          <div class="handson-session">
不要なセッションを削除しました。
[8e48312](https://github.com/cloudnativedaysjp/dreamkast/pull/1556/commits/8e483122f38928613ce1c83fc5c5fa99914f45b0)

2022-10-18 15:20 UTC, tkc66-buzz commented on app/views/contents/cndt2022_hands_on.html.erb
> +            <h5 id="hs3"><strong>『OCI DevOps で体験する CI/CD パイプライン』 by 市川豊 / 仁井田拓也</strong></h5>
申し込み順に変更しました。
[8e48312](https://github.com/cloudnativedaysjp/dreamkast/pull/1556/commits/8e483122f38928613ce1c83fc5c5fa99914f45b0)

2022-10-18 15:31 UTC, tkc66-buzz commented on app/views/contents/cndt2022_hands_on.html.erb
> +        </div>
upstream trainingを追加しました。
[9494af8](https://github.com/cloudnativedaysjp/dreamkast/pull/1556/commits/9494af8e9297dfa4977cfa1146833eae855d333f)

2022-10-19 01:18 UTC, MasayaAoyama commented on app/views/contents/cndt2022_hands_on.html.erb
> +                開催日時：2022/11/18 14:00-16:00
```suggestion
                開催日時：2022/11/18 15:30-18:00
```

2022-10-19 01:18 UTC, MasayaAoyama commented on app/views/contents/cndt2022_hands_on.html.erb
> +                  申し込みURL：<a href="https://ochacafe.connpass.com/">https://ochacafe.connpass.com/</a>
```suggestion
                  申し込みURL：<a href="https://ochacafe.connpass.com/event/262488/">https://ochacafe.connpass.com/event/262488/</a>
```

2022-10-19 01:18 UTC, MasayaAoyama commented on app/views/contents/cndt2022_hands_on.html.erb
> +              午後 (14:00–):</b>
```suggestion
              午後 (14:00–18:00):</b>
```

2022-10-19 01:38 UTC, merged