各Talkの座席数を設定するためにRoomモデルを追加
cloudnativedaysjp/dreamkast pull request #1559
Opened 2022-10-18 13:10 UTC by takaishi

管理画面にRoomsページを追加した。ここから各部屋の座席数を変更すると、部屋に紐付くTrack配下のTalkについて座席数を更新する。

![image](https://user-images.githubusercontent.com/107187/196438786-05f67606-8b36-4b84-8f82-9388a910a5a6.png)

2022-10-18 14:18 UTC, takaishi commented
CIコケとる…

2022-10-19 01:31 UTC, jacopen requested changes

2022-10-19 01:31 UTC, jacopen commented on db/migrate/20221018113936_create_room_table.rb
> +      t.text :description, null: false
<img width="715" alt="image" src="https://user-images.githubusercontent.com/79102/196576087-48c39902-495b-4ee9-90e5-4a792f730453.png">

2022-10-19 09:47 UTC, jacopen approved these changes

2022-10-19 09:48 UTC, merged