Implement checkin
cloudnativedaysjp/dreamkast pull request #1612
Opened 2022-11-03 05:56 UTC by jacopen

チェックイン機能(の表ルート)を実装。

/:event/profiles/checkin  にアクセスするとチェックイン処理が行われてProfileにフラグが立つ。
/:event/profiles/checkinは会場にQRコードを掲示しておき、アクセスさせる仕組み。

ただこれまでの仕組みでは未ログインは強制的にイベントのトップにリダイレクトされる仕組みだったので、そうではなくオリジンのPathを保持したままAuth0ログインさせるようにフローを変更した。

スマホでチェックインできない人向けの裏ルート(受付担当がやるやつ) については別途実装

2022-11-03 09:42 UTC, takaishi reviewed
1日目と2日目それぞれで受付作業があると思うけど、今の実装だとそれには対応できないよね。それは問題ない？

2022-11-03 11:15 UTC, jacopen commented
今回のイベントに関しては1日目も2日目もいける通しチケットしかないので、受付も1回しかしない予定。

今後1日目2日目それぞれで受付やる要件があれば、tickets/ordersを各曜日ごとに発行して、それに対してcheckinする形がいいかなと

2022-11-04 13:13 UTC, takaishi commented
よさそう

2022-11-05 08:19 UTC, takaishi requested changes

2022-11-05 08:19 UTC, takaishi commented on db/migrate/20221104153701_move_check_in_flag.rb
> +    remove_column :profiles, :checked, :boolean
profileへのカラム追加は不要になっているので、migrationファイル自体を消してほしい

2022-11-05 08:19 UTC, takaishi commented on db/migrate/20221104153701_move_check_in_flag.rb
> +    add_column :orders, :checked, :boolean, null: false, default: false
checkin 用の tableを作って、そこでProfileとOrderを紐付ける方がデータ構造としていいかなと思った。

2022-11-05 08:19 UTC, takaishi commented on app/views/profiles/checkin.html.erb
> +        <h2 class="text-center"><%= @conference.abbr.upcase %>へようこそ！</h2>
少し待つとダッシュボードにリダイレクトして、そこでイベントに関する情報を見られることを書いておくと導線としていいと思った

2022-11-05 08:21 UTC, jacopen commented on db/migrate/20221104153701_move_check_in_flag.rb
> +    remove_column :profiles, :checked, :boolean
これちょっと悩んだんだけど、migrationファイル自体を消すとこのPRのReview Appが死ぬなーとおもってこうした。PR出し直した方がいいかな？

2022-11-05 08:26 UTC, takaishi commented on db/migrate/20221104153701_move_check_in_flag.rb
> +    remove_column :profiles, :checked, :boolean
ラベル漬け外ししてReviewApp作り直したらいけるで

2022-11-05 08:27 UTC, jacopen commented on db/migrate/20221104153701_move_check_in_flag.rb
> +    add_column :orders, :checked, :boolean, null: false, default: false
どうだろう、1Orderに対してNチェックインがありうるならそっちのほうがいいんだけど、1:1が確実な場合分けるメリットってどんな感じかなーと
ちょっとモデル増えすぎて把握しづらくなってきてるのも気になりポイント

2022-11-05 08:27 UTC, jacopen commented on db/migrate/20221104153701_move_check_in_flag.rb
> +    remove_column :profiles, :checked, :boolean
あーなるほど、そうしよう

2022-11-05 08:30 UTC, takaishi commented on db/migrate/20221104153701_move_check_in_flag.rb
> +    add_column :orders, :checked, :boolean, null: false, default: false
Orderのcheckというのが何か、がわかりにくいと思ったので、より具体的なカラム名になったらテーブル分けなくてもいいかもしれないな

2022-11-05 08:33 UTC, jacopen commented on db/migrate/20221104153701_move_check_in_flag.rb
> +    add_column :orders, :checked, :boolean, null: false, default: false
今回の処理自体が 'checkin' なので、check-inされたorderの状態を示すのは受動態である 'checked' しかないかなぁと

2022-11-05 08:35 UTC, jacopen commented on app/views/profiles/checkin.html.erb
> +        <h2 class="text-center"><%= @conference.abbr.upcase %>へようこそ！</h2>
リダイレクトまで3秒しかないので、「ダッシュボードにリダイレクトされます」とのみ明記する形にした(それ以上書いても読めなさそうなので)

2022-11-05 08:42 UTC, takaishi commented on db/migrate/20221104153701_move_check_in_flag.rb
> +    add_column :orders, :checked, :boolean, null: false, default: false
そうすると、やはりテーブルを分けたい。Orderというのは複数のチケットと紐づくモデルで、参加のためのチケット以外にも使えるように作ってある。チェックインでOrderのカラムにフラグをたてるよりはチェックインレコードを作る方が構造としては自然。

2022-11-05 08:43 UTC, jacopen commented on db/migrate/20221104153701_move_check_in_flag.rb
> +    add_column :orders, :checked, :boolean, null: false, default: false
なるほど

2022-11-05 08:46 UTC, jacopen commented on db/migrate/20221104153701_move_check_in_flag.rb
> +    add_column :orders, :checked, :boolean, null: false, default: false
checkinモデルを作るとなると、そのrelationはorderだけでいいかな？order自体がprofileと結びついているから、checkinもprofileに結ぶ必要はないかな？と

2022-11-05 08:50 UTC, takaishi commented on db/migrate/20221104153701_move_check_in_flag.rb
> +    add_column :orders, :checked, :boolean, null: false, default: false
書いている通り、OrderとrelationがあればProfileへはなくても大丈夫だと思う。ただ、OrderとTicketがN:NなのでCheckInモデルはProfileもしくはOrderに加えてTicketへのrelationが必要かな。1日目のチケットと2日目のチケット、パーティー参加用のチケット1つのOrderで扱うと考えるとCheckInはTicket単位で扱えないといけないはず。

2022-11-05 08:50 UTC, jacopen commented on db/migrate/20221104153701_move_check_in_flag.rb
> +    add_column :orders, :checked, :boolean, null: false, default: false
あぁ～、結構複雑だ・・・
ちょっと絵にする

2022-11-05 12:57 UTC, takaishi approved these changes
lgtm

2022-11-05 13:13 UTC, merged