feat:Add dkf-api to swagger
cloudnativedaysjp/dreamkast pull request #1618
Opened 2022-11-04 14:34 UTC by ystkfujii

dreamkast-functionのAPIをswaggerに追加しました

- 最終的には全部API Gateway側にもって行くことを踏まえて既存のswaggerに記載しています
  - ref: https://cloudnativedays.slack.com/archives/C015CN1PQ06/p1664811400470069?thread_ts=1664725985.946559&cid=C015CN1PQ06

2022-11-04 14:39 UTC, ystkfujii commented
- swagger追加にあたりdkfunciton側の定義も変更したので、こちらのApproveも併せてお願いいたします 🙇 
  - https://github.com/cloudnativedaysjp/dreamkast-functions/pull/39

2022-11-04 16:04 UTC, jacopen requested changes

2022-11-04 16:04 UTC, jacopen commented on schemas/swagger.yml
> +  /{eventName}/talks/{talkId}/vote:
あ、ちなみにVoteのところにコメント付けちゃってますが、こっちは既に機能としてはCFPが終わって役割終えているので優先順位は一段落ちます。
profile/pointのほうが優先順位高めです

2022-11-04 16:12 UTC, ystkfujii commented on schemas/swagger.yml
> +  /{eventName}/talks/{talkId}/vote:
> 揃えていきたいなと。

同意です。
ただその場合、viewer_countがもろ被りしちゃって名前を変える必要がありそうなんですよね... 🤔 

https://github.com/cloudnativedaysjp/dreamkast/blob/e26a733ad8c0f752bc340ecc9422c0ba0a6b04d3/schemas/swagger.yml#L120

2022-11-04 16:20 UTC, ystkfujii commented on schemas/swagger.yml
> +  /{eventName}/talks/{talkId}/vote:
> この変更をしてもらうとしたとき、どのくらい手間かかりそうですか？

変更した場合、現状pathで受け取ってるeventNameの受け取り方が見えてないので何ともです。
とりあえず明日みてみます！

11/6のリハーサルでviewer_countの動作確認ができるのかなと思っていて、それまでには切り替えたい気持があります。なので適度なとこで諦める予定です 🙏

2022-11-04 16:23 UTC, jacopen commented on schemas/swagger.yml
> +  /{eventName}/talks/{talkId}/vote:
> ただその場合、viewer_countがもろ被りしちゃって名前を変える必要がありそうなんですよね...
こちらは被っちゃっていいかなと思います。REST APIとしてのviewer_countは現時点でDkUIしか叩いていないため、DkUIがfunctionのほうを向けばDk側のAPIは無効にしちゃえばいいかなと

2022-11-05 06:52 UTC, ystkfujii commented on schemas/swagger.yml
> +  /{eventName}/talks/{talkId}/vote:
下記の対応しました！

- 全てのURLのpathが/api/v1から始まるように修正しました
- URLのpathからeventNameを削除しました
- DK側のviewer_countは削除しました 
- 表記のもろもろ
  - camel caseとかeventAbbrとか

DkF側の修正PRはこちらになります
  - https://github.com/cloudnativedaysjp/dreamkast-functions/pull/41
 
すこし重たい感じになっていますがレビューよろしくお願いいたします 🙇

2022-11-05 08:29 UTC, takaishi reviewed
lgtmです！

2022-11-05 09:15 UTC, jacopen approved these changes

2022-11-05 09:16 UTC, merged

2022-11-05 09:19 UTC, ystkfujii commented
swagger生成元のこちら https://github.com/cloudnativedaysjp/dreamkast-functions/pull/41
 もApprove お願いいたします 🙇