add rake task to add intermissions
cloudnativedaysjp/dreamkast pull request #1651
Opened 2022-11-15 09:42 UTC by takaishi

https://github.com/cloudnativedaysjp/dreamkast/issues/1643

2022-11-15 09:54 UTC, TakumaNakagame commented
外出のため、本日夜確認します

2022-11-15 09:55 UTC, takaishi commented
%w使わせてくれ

2022-11-15 10:49 UTC, jacopen requested changes

2022-11-15 10:49 UTC, jacopen commented on lib/tasks/add_talks_for_cndt2022.rake
> +      %w[18:00:00 18:15:00 クロージング intermission],
夜イベントは1日目にしかない & 2日目のクロージングは長めに設定される　という違いがあるので、1日目と2日目で異なるtalkを入れられるようにしておいてほしいです！

実際の時間やタイトルは追って連絡します

2022-11-15 10:50 UTC, takaishi commented on lib/tasks/add_talks_for_cndt2022.rake
> +      %w[18:00:00 18:15:00 クロージング intermission],
あーなるほど。

2022-11-16 09:56 UTC, takaishi commented
時間とタイトルが確定したらアップデートしてマージする予定。

2022-11-19 16:56 UTC, jacopen requested changes

2022-11-19 16:56 UTC, jacopen commented on lib/tasks/add_talks_for_cndt2022.rake
> +      %w[18:00:00 18:15:00 クロージング intermission],
```suggestion
      %w[18:00:00 18:20:00 夜イベントは18:20から開催します。しばらくお待ちください intermission],
```

2022-11-19 16:56 UTC, jacopen commented on lib/tasks/add_talks_for_cndt2022.rake
> +      %w[18:15:00 20:00:00 夜イベント(仮) intermission],
```suggestion
      %w[18:20:00 20:00:00 夜イベント(仮) intermission],
```

2022-11-19 16:56 UTC, jacopen commented on lib/tasks/add_talks_for_cndt2022.rake
> +      %w[18:00:00 18:15:00 トラックAにてクロージングを配信中！ intermission],
```suggestion
      %w[18:00:00 18:20:00 夜イベントは18:20から開催します。しばらくお待ちください intermission],
```

2022-11-19 16:56 UTC, jacopen commented on lib/tasks/add_talks_for_cndt2022.rake
> +      %w[18:15:00 20:00:00 トラックAにて夜イベント(仮)を配信中！ intermission],
```suggestion
      %w[18:20:00 20:00:00 トラックAにて夜イベントを配信中！ intermission],
```

2022-11-20 01:11 UTC, jacopen approved these changes

2022-11-20 01:11 UTC, merged