add dummy sessions and intermissions for rehearsal
cloudnativedaysjp/dreamkast pull request #1953
Opened 2023-06-17 00:27 UTC by takaishi

https://github.com/cloudnativedaysjp/dreamkast/issues/1950 用のデータを登録するタスクを追加。

2023-06-17 00:32 UTC, takaishi commented on lib/tasks/add_talks_for_cndf2023_rehearsal_intermission.rake
> +      %w[12:20:00 12:25:00 休憩 intermission],
参加者にはセットチェンジ（って何かわかってないけど配信側の用語だと推測）というよりは休憩として見せた方がいいと思ったので休憩としています

2023-06-18 08:17 UTC, jacopen requested changes
タイムテーブルがこちらでFIXになったので。これ準拠に変えて貰えれば！
https://www.notion.so/cloudnativedays/131155479a2c46b4b956b72fd11f2507

2023-06-18 08:17 UTC, jacopen commented on db/fixtures/development/00_seeds.rb
>    {id: 25, date: "2023-08-02", start_time: "12:00", end_time: "18:00", conference_id: 9, internal: false}, # 前夜祭
前夜祭は表への配信無しになりそうなのでこの行消して貰ってよいです

2023-06-18 08:17 UTC, jacopen commented on db/fixtures/production/00_seeds.rb
>    {id: 25, date: "2023-08-02", start_time: "12:00", end_time: "18:00", conference_id: 9, internal: false}, # 前夜祭
同上

2023-06-18 10:21 UTC, jacopen approved these changes

2023-06-18 10:21 UTC, merged