古い設定ファイルや過去イベント向けのファイル類を削除
cloudnativedaysjp/dreamkast pull request #2012
Opened 2023-09-02 05:54 UTC by oshiro3

ルート下のデプロイファイルや過去に使われていたであろう JS の設定ファイルを削除しました。
また、特定のイベント名の入った JS と rake ファイルを削除していますが、現在も使用予定のものがあればご指摘ください。

2023-09-02 08:41 UTC, jacopen requested changes

2023-09-02 08:41 UTC, jacopen commented on lib/tasks/modify_session_time_for_keynote_cndf2023.rake
> -namespace :db do
このファイルは今後似たようなことをやる可能性が結構あるので参考用に残しておいてもらえれば！

2023-09-02 08:41 UTC, jacopen commented on lib/tasks/add_talks_for_cndf2023_rehearsal_intermission.rake
> -require 'slack/incoming/webhooks'
このファイルは残し

2023-09-02 08:41 UTC, jacopen commented on lib/tasks/add_talks_for_cndf2023_rehearsal_dummy_sessions.rake
> -require 'slack/incoming/webhooks'
このファイルは残し

2023-09-02 08:41 UTC, jacopen commented on lib/tasks/add_talks_for_cndf2023_intermission.rake
> -require 'slack/incoming/webhooks'
このファイルは残し

2023-09-02 11:47 UTC, oshiro3 commented
上記４ファイルレストアしました

2023-09-03 10:52 UTC, jacopen approved these changes

2023-09-03 10:52 UTC, merged