Simplify ticket system
cloudnativedaysjp/dreamkast pull request #2014
Opened 2023-09-03 10:13 UTC by oshiro3

思ったより変更範囲が多くなってしまった感じですがチケットで処理していた部分を Profile の Enum で置き換えるように変更しました。

2023-09-06 09:01 UTC, takaishi requested changes
routes.rbにordersとcancel_ordersが残っているので削除をお願いします！

2023-09-06 09:04 UTC, takaishi commented on app/views/profiles/_form.html.erb
> +      <%= form.label :online, { for: "participation_online" } %>
`現地参加` `リモート参加` などの表記がよさそうです。

![image](https://github.com/cloudnativedaysjp/dreamkast/assets/107187/59461c75-3ba9-4d80-8ad2-f94dde8adee8)

2023-09-06 09:07 UTC, takaishi commented on db/migrate/20230903011944_add_participation_columns_to_profile.rb
> +    add_column :profiles, :participation, :string
現地参加可能な人数は上限があるので、それを管理できるようにしてもらえますか？
チケットの時はticketsテーブルに管理用のカラムがありました。

2023-09-17 02:22 UTC, oshiro3 commented on db/migrate/20230903011944_add_participation_columns_to_profile.rb
> +    add_column :profiles, :participation, :string
定員を Conference に持たせて管理するようにしました。

2023-09-17 02:22 UTC, oshiro3 commented on app/views/profiles/_form.html.erb
> +      <%= form.label :online, { for: "participation_online" } %>
表記を変更しました。

2023-09-17 05:00 UTC, takaishi approved these changes
LGTM!

2023-09-17 05:00 UTC, merged