MediaPackageリソースをStreamingの管理下に移行する
cloudnativedaysjp/dreamkast pull request #2022
Opened 2023-09-09 04:55 UTC by takaishi

2023-09-10 08:13 UTC, jacopen requested changes

2023-09-10 08:13 UTC, jacopen commented on app/models/media_package_origin_endpoint.rb
> +    media_package_client.delete_origin_endpoint(id: endpoint_id)
ここは例外処理がないので、もし間違って手動でAWS側のリソース消しちゃってたりした場合このメソッドがエラーを起こし続け、呼び出し元の後続処理(destroy!) が呼ばれずゴミがDBに残り続けることになったりしないかな

2023-09-10 08:13 UTC, jacopen commented on app/models/media_package_channel.rb
> +    media_package_client.delete_channel(id: channel_id)
ここも例外処理がないのが気になる

2023-09-10 08:13 UTC, jacopen commented on app/jobs/delete_streaming_aws_resources_job.rb
> +      @streaming.media_package_origin_endpoint.delete_aws_resource
もしdelete_aws_resourceを単体で実行したいというケースがあるならこれでいいけど、DBのdestroy!とセットで呼ばれることが確実なのであれば、destroy!をオーバーライドする形で実装したほうが間違いがないかなって思った

2023-09-10 08:48 UTC, takaishi commented on app/models/media_package_origin_endpoint.rb
> +    media_package_client.delete_origin_endpoint(id: endpoint_id)
あっ、リソースの有無をチェックする処理が漏れていた。

2023-09-17 02:30 UTC, takaishi commented
PR増えてきてUIとのインレグレーション確認するのに手間なのでセルフマージします。

2023-09-17 02:30 UTC, merged