Proposalに関する情報をExporterで出力できるようにする(v2)
cloudnativedaysjp/dreamkast pull request #2059
Opened 2023-10-03 09:59 UTC by ryusuketesaki

- models/proposal_item.rbのメソッドをmodels/talk.rbへ変更
- クエリ内容をselectからカウントに変更

2023-10-03 13:56 UTC, jacopen requested changes

2023-10-03 13:56 UTC, jacopen commented on app/models/talk.rb
> +  def self.count_proposal_params
ProposalはTalk modelではなくProposal modelが別に存在するので、Talkモデルに移してしまうのは良くないですね。元の場所か、あるいはProposal modelに実装するのが自然なように思います

2023-10-03 13:56 UTC, jacopen commented on app/models/talk.rb
> +      .group('talks.conference_id', 'proposal_items.label', 'proposal_items.params')
今回の修正内容から察するに、 `CFPの総数をメトリクスとして表示する` という実装に変更したいのかなと推察しています。

その前提に立ったとき、2つ気になるところがありまして

1. データの取り方の問題

実装元になったメソッドは、 `各Proposalの属性` を取得しています。
例えばtalk_id 123は `現地登壇` かつ `初心者向け` かつ `Productionフェーズの話` と言った具合です。
これはProposalごとに持っているデータを表示しており、これをPrometheus/Grafana側で加工することで、CFPごとの属性をグラフにできるようになっています。

しかし、今回は`各Proposalの情報` ではなく `Proposalの総数` をcountするクエリに変わっています。
となると、ここでproposal_itemsを取得している意味が無くなってしまいますし、Exporterに表示される
```
labels: { conference_id: proposal_items.conference_id, proposal_items_label: proposal_items.label, proposal_items_params: proposal_items.params }
```
の値はウソの値が入ってしまうことになります。

ちなみに、Proposalのカウントを取りたいだけであればクラスメソッドを実装する必要はなく
```
# conference_id: 10はCNDT2023
Conference.find(10).proposals.count
```
を呼ぶだけでカウントできます。
全てのカンファレンスのProposal数を出すなら

```
Conference.all.each{|c| puts c.proposals.count}
```
みたいな形でループさせればとれますね

2. 元のメソッドを変更することについて

今回は元あったメソッドを変更してカウントを表示する形に変更しています。
メソッドを追加するのではなく、変更する形にしたのはなぜでしょう？ 
今後これまで取っていたメトリクスを利用することは絶対にない、あるいはメトリクスを取ることによってなんらしかの不都合がある というのであれば分かりますが、そういった理由がないのであれば新規追加で良いのでは？と思った次第でした。
何らしかの意図がありそうしたのであれば教えてください。

2023-10-11 15:18 UTC, ryusuketesaki commented on app/models/talk.rb
> +      .group('talks.conference_id', 'proposal_items.label', 'proposal_items.params')
@jacopen 
元あったメソッド`dreamkast_select_proposal_items`ですが、本件の対応の中で新規作成したメソッドになります。
[前回のPR](https://github.com/cloudnativedaysjp/dreamkast/pull/2028)でmergeしました。

この状態で[Prometheus/Grafana側](https://grafana.dev.cloudnativedays.jp/d/ta0UrWZSz/cndt2023-proposal?orgId=1&from=now-30d&to=now)で加工しようとしていたのですが、件数が正しく取得できなかったので、本PRで変更を試してみた状態でした。

今回取得したかったメトリクスについてはlabelsに`talk_id`を追加することで解消できるかと考えているので、本PRはcloseして[こちらのPR](https://github.com/cloudnativedaysjp/dreamkast/pull/2064)に移行したいと思います。

2023-10-11 15:20 UTC, ryusuketesaki commented
#2064 に移行して本PRはcloseします。

2023-10-11 15:20 UTC, closed without merging