fix: when document.readyState isn't loading, need to run addEventListener immedeately.
cloudnativedaysjp/dreamkast pull request #2287
Opened 2024-04-22 13:45 UTC by takaishi

https://qiita.com/sho_fcafe/items/192bf0b97b1d84f762ce

2024-04-22 13:56 UTC, jacopen requested changes

2024-04-22 13:56 UTC, jacopen commented on app/javascript/packs/speaker_form.js
> +const removeTalkFieldListener = () => {
これだとTalkFieldListenerを削除するように読めてしまうので、メソッド名変えたいところ
英語としては変だけど、他の命名でも `addDeleteButtonListener` みたいなのがあったりするので、

```suggestion
const addRemoveTalkFieldListener = () => {
```
とかかなぁ

2024-04-22 23:37 UTC, takaishi commented on app/javascript/packs/speaker_form.js
> +const removeTalkFieldListener = () => {
あー、確かに。

2024-04-24 10:52 UTC, takaishi commented on app/javascript/packs/speaker_form.js
> +const removeTalkFieldListener = () => {
https://github.com/cloudnativedaysjp/dreamkast/pull/2287/commits/01c16ad3cd94dc4b64d4fd7146a9836f8b7ad0e2 でリネームしてみた。

2024-04-24 10:53 UTC, jacopen approved these changes

2024-04-24 10:59 UTC, merged