PDF 参加表の生成
cloudnativedaysjp/dreamkast pull request #2435
Opened 2024-11-03 04:49 UTC by oshiro3

PDF参加表を生成するジョブを作成しました.

基本方針は Public な entry_sheet ページを作成して chromium(ferrum) を利用してレンダリング. その結果を PDF に書き起こすという方向にしました.

Public なページで個人に関わるものが出せるとまずいため Rails の Encrypter で暗号化したクエリパラメータを投げるようにしています.

またヘッダーとフッターを非表示にするために Layout を新たに作成しています.

rake task や Rails Console から `GenerateEntrysheetJob.perform_now($ConferenceId, $ProfileId, $SpeakerId)` で実行できます.

2024-11-06 10:56 UTC, takaishi requested changes
CIが落ちているようです！

2024-11-06 13:55 UTC, oshiro3 commented
CI修正しました！

2024-11-10 11:36 UTC, takaishi commented on app/controllers/entry_sheet_controller.rb
> +  def show
- UIでスキャンした際に印刷されると思うので、APIとして実装が必要な気がしました (Api::V1::CheckInConferencesController内で呼び出す必要がありそう）

2024-11-15 13:43 UTC, oshiro3 commented on app/controllers/entry_sheet_controller.rb
> +  def show
Api::V1::CheckInConferencesController のcheckin 時に呼び出すようにしました。
1点問題があって Speaker 表示をする際には SpeakerId を渡す必要がありますが、Profile の情報からでは難しい気がしています。
Speaker は別のフローでチェックインしてもらう or 別途印刷するなどの運用がいる可能性がありそうでしょうか？

2024-11-15 13:45 UTC, oshiro3 commented
申し訳ないのですが、ちょっと土日が対応難しく最速で月曜日中の追加対応になりそうです。。。
リハなどで急ぎで必要であれば P/R 引き継いでいただけると助かります（月~火曜で大丈夫であれば最優先で対応しますが。。。）

2024-11-16 06:29 UTC, takaishi commented on app/controllers/entry_sheet_controller.rb
> +  def show
同じemailを持つSpeakerがいたらSpeakerとみなしているので取得可能だと思います

2024-11-17 06:21 UTC, takaishi approved these changes

2024-11-17 06:21 UTC, merged