スタンプラリー改善
cloudnativedaysjp/dreamkast pull request #2436
Opened 2024-11-03 10:16 UTC by takaishi

- チェックポイントをD&Dで並べ替え可能にする
- チェックイン一覧の見た目をよくする
- ページのレイアウト調整

2024-11-10 02:22 UTC, jacopen requested changes
動作確認した結果見られていること

- CP Link
  - ログインしている状態だと正しく動く
  - ログイン出来ていない状態だと、チェックインのボタンは表示されるが、ボタンを押すとInternal Server Error
    - 未ログインの場合、ログイン画面に飛ばされるのが望ましい
- QRコード
  - 読み取ると404になってしまう (ログイン・未ログインともに)

2024-11-10 02:27 UTC, jacopen commented
QRコードから読み取れるリンク
```
http://dreamkast-dk-2436.dev.cloudnativedays.jp/cndw2024/stamp_rally_check_ins/new?stamp_rally_check_point=01JC9XN1SE1EB51VK39VAZJV5T
```

CP Link
```
https://dreamkast-dk-2436.dev.cloudnativedays.jp/cndw2024/stamp_rally_check_ins/new?stamp_rally_check_point_id=01JC9XN1SE1EB51VK39VAZJV5T
```

パラメータが `stamp_rally_check_point_id` じゃなくて `stamp_rally_check_point` になってしまっているのが原因か？

2024-11-10 02:32 UTC, jacopen commented
既にチェックイン済みのところに再度チェックインすると、Internal Server Error
これはチェックイン済みですみたいなのを出す方が親切かも

2024-11-10 02:36 UTC, jacopen commented
![CleanShot 2024-11-10 at 11 35 22](https://github.com/user-attachments/assets/37016142-5e29-4014-92be-cf783c7e984d)
いろいろスタンプ作って試していたら、どのリンクを押してもInternal Server Errorが出るようになってしまった、変なステートに落ち込んでしまっている様子

2024-11-10 02:40 UTC, jacopen commented
あー、Internal Server Errorについてはチェック中にMySQLがリセットされてしまったのが原因かもしれない

2024-11-16 03:09 UTC, jacopen requested changes

2024-11-16 03:09 UTC, jacopen commented on app/views/stamp_rally_check_ins/new.html.erb
>          <p>スタンプラリーを全て回り終わりました。フィニッシュしますか？</p>
全て回り終わって無くてもFinishすることは可能なので、違和感がないように表記を変更

```suggestion
        <p>スタンプラリーをフィニッシュしますか？</p>
```

2024-11-16 03:10 UTC, jacopen reviewed
今は読み込むと「チェックインしますか？」の画面になり、そこでボタンを押すとチェックインとなるけど、読み込んだら即座にチェックインされる方がユーザーフレンドリーかなと思った

2024-11-16 03:12 UTC, jacopen commented on app/views/stamp_rally_check_ins/new.html.erb
>          <p>スタンプラリーを全て回り終わりました。フィニッシュしますか？</p>
📝 今回ブース数が多いため全てを回りきるのは難易度が高い。なので、指定の個数を満たすとFinish可とする可能性が高い
その指定の個数はこれから要調整

2024-11-16 04:13 UTC, takaishi commented on app/views/stamp_rally_check_ins/new.html.erb
>          <p>スタンプラリーを全て回り終わりました。フィニッシュしますか？</p>
>今回ブース数が多いため全てを回りきるのは難易度が高い。なので、指定の個数を満たすとFinish可とする可能性が高い

なるほど

2024-11-16 13:33 UTC, jacopen reviewed
一通りチェックイン試したら、こういうエラーが出るようになった
```

I, [2024-11-16T13:31:34.154903 #37]  INFO -- : [6b06d46b-a755-4af0-972f-de75b315932b] Started GET "/cndw2024/stamp_rally_check_ins" for 153.199.14.107 at 2024-11-16 13:31:34 +0000
--
I, [2024-11-16T13:31:34.156068 #37]  INFO -- : [6b06d46b-a755-4af0-972f-de75b315932b] Processing by StampRallyCheckInsController#index as HTML
I, [2024-11-16T13:31:34.156108 #37]  INFO -- : [6b06d46b-a755-4af0-972f-de75b315932b]   Parameters: {"event"=>"cndw2024"}
I, [2024-11-16T13:31:34.174359 #37]  INFO -- : [6b06d46b-a755-4af0-972f-de75b315932b]   Rendered stamp_rally_check_ins/index.html.erb within layouts/application (Duration: 10.3ms \| Allocations: 2420)
I, [2024-11-16T13:31:34.174446 #37]  INFO -- : [6b06d46b-a755-4af0-972f-de75b315932b]   Rendered layout layouts/application.html.erb (Duration: 10.5ms \| Allocations: 2488)
E, [2024-11-16T13:31:34.174664 #37] ERROR -- : [6b06d46b-a755-4af0-972f-de75b315932b] Rendering 500 with exception: Invalid status
E, [2024-11-16T13:31:34.174778 #37] ERROR -- : [6b06d46b-a755-4af0-972f-de75b315932b] /app/app/views/stamp_rally_check_ins/index.html.erb:33:in `_app_views_stamp_rally_check_ins_index_html_erb___1608565561822380479_117320'
/usr/local/bundle/gems/actionview-7.0.8.1/lib/action_view/base.rb:244:in `public_send'
/usr/local/bundle/gems/actionview-7.0.8.1/lib/action_view/base.rb:244:in `_run'
/usr/local/bundle/gems/actionview-7.0.8.1/lib/action_view/template.rb:157:in `block in render'
/usr/local/bundle/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb:206:in `block in instrument'
/usr/local/bundle/gems/activesupport-7.0.8.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/bundle/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb:206:in `instrument'
/usr/local/bundle/gems/actionview-7.0.8.1/lib/action_view/template.rb:361:in `instrument_render_template'
/usr/local/bundle/gems/actionview-7.0.8.1/lib/action_view/template.rb:155:in `render'

```

2024-11-16 15:05 UTC, jacopen approved these changes
LGTM!

2024-11-16 15:05 UTC, merged