adminページの複数イベント対応
cloudnativedaysjp/dreamkast pull request #376
Opened 2021-01-02 02:49 UTC by takaishi

ref: https://github.com/cloudnativedaysjp/dreamkast/issues/368

2021-01-08 14:00 UTC, jacopen commented on app/controllers/event_controller.rb
> +    @current_user[:extra][:raw_info]["https://cloudnativedays.jp/roles"].include?("CNDT2020-Admin")
これ、 `${@conference.abbr.upcase}-Admin` みたいにすればイベントごとにAdmin設定できないかな

2021-01-09 01:01 UTC, takaishi commented on app/controllers/event_controller.rb
> +    @current_user[:extra][:raw_info]["https://cloudnativedays.jp/roles"].include?("CNDT2020-Admin")
あー、できるね

2021-01-09 05:35 UTC, jacopen commented
見つけた点2つ

・CNDO2021-AdminでなくてもAdminページが見えてしまった
たぶんこのあたりの修正が必要。というか、eventのほうは何用途だっけ。。。もしかしたら統合が必要かも？
https://github.com/cloudnativedaysjp/dreamkast/blob/fff2aa7c4e9f28bae2da5a7a0f4b50f56ac1be37/app/controllers/concerns/secured.rb#L25-L27

・adminページに飛ぼうとするとProfile入力が求められる
これはCNDTじゃなくてCNDOのProfile入力 ってことでいいかな？
![image](https://user-images.githubusercontent.com/79102/104084103-defb3600-5287-11eb-822b-a6a0f8dc7f74.png)

2021-01-09 05:36 UTC, jacopen requested changes
.

2021-01-09 06:04 UTC, takaishi commented
>これはCNDTじゃなくてCNDOのProfile入力 ってことでいいかな？

yes.

2021-01-09 06:07 UTC, takaishi commented
>たぶんこのあたりの修正が必要。というか、eventのほうは何用途だっけ。。。もしかしたら統合が必要かも？

admin? はevent_headerで必要なんだけど、event_controllerではSecuredをincludeしてないんだよね。
securedで定義されているbefore_actionsをevent_controllerでは発火させたくないというのがある。

2021-01-09 06:30 UTC, takaishi commented
>dmin? はevent_headerで必要なんだけど、event_controllerではSecuredをincludeしてないんだよね。
securedで定義されているbefore_actionsをevent_controllerでは発火させたくないというのがある（redirectされるとこまる）

securedに集約できたのでした。

2021-01-09 06:51 UTC, jacopen approved these changes

2021-01-09 06:51 UTC, jacopen commented
LGTM!!

2021-01-09 06:51 UTC, merged