タイムテーブル編成のための画面を追加する
cloudnativedaysjp/dreamkast pull request #426
Opened 2021-02-06 17:05 UTC by takaishi

2021-02-07 06:54 UTC, jacopen commented
CI通ったらみましゅ

2021-02-07 07:43 UTC, takaishi commented
コンフリクトしてる…

2021-02-07 09:04 UTC, jacopen requested changes
これ残ってるとうっかり事故りそうなので、cndo2021のときは非表示にしてほしいです

![image](https://user-images.githubusercontent.com/79102/107141860-df621c00-696e-11eb-99bf-c16e8d23691d.png)

2021-02-07 09:09 UTC, jacopen requested changes
Review appsで/cndo2021/admin/timetablesを開くと500で死んでしまった。
Review appsのモックデータには想定している値がないものがあるのかもしれない。

コーナーケースかもしれないけど、モックデータを修正するとか値が無くても出るようにするとかしたほうがいいかも
```
2021-02-07T09:05:58.961956+00:00 app[web.1]: I, [2021-02-07T09:05:58.961832 #10]  INFO -- : [57c0af83-8cd5-4338-8dd5-2c10e2c44b47]   Rendered admin/timetables/index.html.erb within layouts/application (Duration: 56.4ms | Allocations: 3738)
2021-02-07T09:05:58.962155+00:00 app[web.1]: E, [2021-02-07T09:05:58.962056 #10] ERROR -- : [57c0af83-8cd5-4338-8dd5-2c10e2c44b47] Rendering 500 with exception: undefined method `strftime' for nil:NilClass
2021-02-07T09:05:58.962310+00:00 app[web.1]: E, [2021-02-07T09:05:58.962215 #10] ERROR -- : [57c0af83-8cd5-4338-8dd5-2c10e2c44b47] /app/app/views/admin/timetables/index.html.erb:43:in `block (3 levels) in _app_views_admin_timetables_index_html_erb___528439140258682072_42080'
2021-02-07T09:05:58.962311+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
2021-02-07T09:05:58.962311+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
2021-02-07T09:05:58.962331+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/helpers/capture_helper.rb:45:in `capture'
2021-02-07T09:05:58.962331+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/helpers/form_helper.rb:1009:in `fields_for'
2021-02-07T09:05:58.962332+00:00 app[web.1]: /app/app/views/admin/timetables/index.html.erb:27:in `block (2 levels) in _app_views_admin_timetables_index_html_erb___528439140258682072_42080'
2021-02-07T09:05:58.962332+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/relation/delegation.rb:87:in `each'
2021-02-07T09:05:58.962333+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/relation/delegation.rb:87:in `each'
2021-02-07T09:05:58.962333+00:00 app[web.1]: /app/app/views/admin/timetables/index.html.erb:26:in `block in _app_views_admin_timetables_index_html_erb___528439140258682072_42080'
2021-02-07T09:05:58.962334+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
2021-02-07T09:05:58.962334+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
2021-02-07T09:05:58.962335+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/helpers/capture_helper.rb:45:in `capture'
2021-02-07T09:05:58.962335+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/helpers/form_helper.rb:755:in `form_with'
```

2021-02-07 13:47 UTC, jacopen commented
セッション登録したやつがなんかタイムテーブルに出なくて調べ中
![image](https://user-images.githubusercontent.com/79102/107148430-4fd06380-6996-11eb-96db-c2bf596cc372.png)
![image](https://user-images.githubusercontent.com/79102/107148442-62e33380-6996-11eb-8813-c86c737c6479.png)

2021-02-07 13:51 UTC, jacopen requested changes
登録セッションがタイムテーブルに出ない理由、conference_day_idがNULLなのが原因だった。
確かに時間だけでなくて日付の設定も必要になるので、プルダウンでconference_dayを指定できる機能が必要だね

2021-02-07 13:53 UTC, jacopen commented
あぁそうか、dateカラムに入れているからか。
実際にはdateは使われていなくて、conference_day_idのほうをみてます。なので、conference_day_idを指定する機能は必須。dateは入れても良いし、入れなくてもいいって感じ

2021-02-07 13:53 UTC, takaishi commented
あーそうだっけか…

2021-02-07 17:04 UTC, jacopen commented
あー、今回の修正とは別問題で死んでしまった。
エントリーされた情報には難易度の設定がないので、タイムテーブル表示時に死んでしまう。

```
2021-02-07T17:01:50.143731+00:00 app[web.1]: I, [2021-02-07T17:01:50.143657 #10]  INFO -- : [3c0fede2-ac52-4c84-94e4-3c3f5856668d]   Rendered timetable/index.html.erb within layouts/application (Duration: 54.0ms | Allocations: 8684)
2021-02-07T17:01:50.143896+00:00 app[web.1]: E, [2021-02-07T17:01:50.143821 #10] ERROR -- : [3c0fede2-ac52-4c84-94e4-3c3f5856668d] Rendering 500 with exception: Couldn't find TalkDifficulty without an ID
2021-02-07T17:01:50.144040+00:00 app[web.1]: E, [2021-02-07T17:01:50.143935 #10] ERROR -- : [3c0fede2-ac52-4c84-94e4-3c3f5856668d] /app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/relation/finder_methods.rb:431:in `find_with_ids'
2021-02-07T17:01:50.144041+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/relation/finder_methods.rb:69:in `find'
2021-02-07T17:01:50.144042+00:00 app[web.1]: /app/app/controllers/application_controller.rb:42:in `talk_difficulty'
```

難易度、どうするかなぁ

2021-02-08 10:25 UTC, takaishi commented
とりあえず難易度が無くても表示するように変更。難易度が後で必要になったら編成フォームから設定可能にする。

2021-02-08 10:51 UTC, takaishi commented
今気づいたけどEnd Time入力する必要ないな？セッション時間から自動的に算出できるやん？

2021-02-08 14:05 UTC, jacopen requested changes
タイムテーブル上のリンククリックで出るモーダル側も修正必要そう
![image](https://user-images.githubusercontent.com/79102/107230204-16652a00-6a62-11eb-95b9-098eb356525b.png)

2021-02-09 09:13 UTC, jacopen commented
上記エラーはこんな内容だった
```
2021-02-09T09:10:33.406788+00:00 app[web.1]: I, [2021-02-09T09:10:33.406723 #10]  INFO -- : [112882fe-d0e6-4a11-add1-9c7bc622b241]   Rendered talks/show.js.erb (Duration: 2.6ms | Allocations: 689)
2021-02-09T09:10:33.407001+00:00 app[web.1]: E, [2021-02-09T09:10:33.406916 #10] ERROR -- : [112882fe-d0e6-4a11-add1-9c7bc622b241] Rendering 500 with exception: undefined method `name' for nil:NilClass
2021-02-09T09:10:33.407218+00:00 app[web.1]: E, [2021-02-09T09:10:33.407099 #10] ERROR -- : [112882fe-d0e6-4a11-add1-9c7bc622b241] /app/app/views/talks/_show_modal.html.erb:15:in `_app_views_talks__show_modal_html_erb___1048123388039681963_42260'
2021-02-09T09:10:33.407219+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/base.rb:274:in `_run'
2021-02-09T09:10:33.407226+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/template.rb:185:in `block in render'
2021-02-09T09:10:33.407227+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:182:in `instrument'
2021-02-09T09:10:33.407227+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/template.rb:385:in `instrument_render_template'
```

_show_modal.html.erbのほうで修正が必要そうなので、さくっと入れちゃう

2021-02-09 09:30 UTC, jacopen approved these changes

2021-02-09 09:32 UTC, jacopen commented
自分のほうで修正積んで動くことを確認した。コードレビューの方はOKなので、 高石先生の方で  
https://github.com/cloudnativedaysjp/dreamkast/pull/426/commits/fa3b97f7aeabdace41cb4ebb1a7525407dfad141
を確認してもらって問題なさそうならマージで

2021-02-09 09:36 UTC, takaishi commented
コミットあざます。問題なさそうなのでマージします

2021-02-09 09:36 UTC, merged