Add CI/CD Conf
cloudnativedaysjp/dreamkast pull request #677
Opened 2021-05-27 17:46 UTC by jacopen

2021-05-28 19:03 UTC, jacopen commented
今後の作業分担のために一旦現段階のをPullRequest。

2021-05-30 01:26 UTC, takaishi requested changes
スピーカーとしてエントリーした後speaker_dashboardを見るとInternalErrorになるぽいです

2021-05-30 01:26 UTC, takaishi commented on db/fixtures/development/seeds.rb
> +    status: 0,
statusをseedで管理するとmigrate時に変わることがあるのでやらないようにしたい

2021-05-30 01:26 UTC, takaishi commented on db/fixtures/production/seeds.rb
> +    status: 0,
developmentと同様statusはseedで管理したくない

2021-05-30 04:45 UTC, jacopen commented
なおした！

2021-05-30 07:22 UTC, takaishi approved these changes

2021-05-30 07:22 UTC, merged