CFP の新規作成時にメール送信する
cloudnativedaysjp/dreamkast pull request #703
Opened 2021-06-12 03:43 UTC by oshiro3

#701  

- create からは無条件にメール送信
- update の際は talk_id を保存して save の結果と比較することで create を判定

## 特にレビューが欲しいところ

- メール文面
- 本番環境の SES 動きますよねという確認(@takaishi さんのメールが認証されているだけだったので動くのか気になりました)
- エスケープしてないので改行が入ると文面が崩れますけど、対応が必要かどうか

## スクショ
![スクリーンショット 2021-06-11 213959](https://user-images.githubusercontent.com/40717789/121689434-8dd5c380-caff-11eb-9c93-eeb664aed5aa.png)

2021-06-13 07:28 UTC, takaishi requested changes

2021-06-13 07:28 UTC, takaishi commented on app/views/speaker_mailer/cfp_registered.text.erb
> +CI/CD Conference 2021の CFP を以下の内容で受け付けました。
カンファレンス名もConferenceオブジェクトから埋め込むようにしてほしいです

2021-06-13 07:28 UTC, takaishi commented on app/views/speaker_mailer/cfp_registered.text.erb
> +CI/CD Conference 2021の CFP を以下の内容で受け付けました。
```suggestion
CI/CD Conference 2021のプロポーザルを以下の内容で受け付けました。
```

2021-06-13 10:24 UTC, oshiro3 commented on app/views/speaker_mailer/cfp_registered.text.erb
> +CI/CD Conference 2021の CFP を以下の内容で受け付けました。
オブジェクトから取得するよう変更しました。

![スクリーンショット 2021-06-13 192417](https://user-images.githubusercontent.com/40717789/121803493-eb434f00-cc7c-11eb-84d7-f8e6f2da9301.png)

2021-06-13 10:24 UTC, oshiro3 commented on app/views/speaker_mailer/cfp_registered.text.erb
> +CI/CD Conference 2021の CFP を以下の内容で受け付けました。
文言を変更しました

2021-06-18 08:39 UTC, takaishi commented on app/mailers/speaker_mailer.rb
> +    mail(to: speaker.email, subject: 'プロポーザルを受け付けました')
追加で気になったところがあった。Subjectにもカンファレンス名（もしくは略称）を書いておく方がいいかなあ？

2021-06-18 08:40 UTC, takaishi commented on app/views/speaker_mailer/cfp_registered.text.erb
> +CI/CD Conference 2021の CFP を以下の内容で受け付けました。
Gooood!!!

2021-06-18 08:40 UTC, takaishi commented on app/views/speaker_mailer/cfp_registered.text.erb
> +CI/CD Conference 2021の CFP を以下の内容で受け付けました。
👍 👍 👍 👍

2021-06-18 09:45 UTC, oshiro3 commented on app/mailers/speaker_mailer.rb
> +    mail(to: speaker.email, subject: 'プロポーザルを受け付けました')
文頭に Conference.name 追加しました。
ちょっと長い気はしますが、悪くないと思います。
![スクリーンショット 2021-06-18 184438](https://user-images.githubusercontent.com/40717789/122541991-32f31d80-d065-11eb-93f5-6df21fb99dfc.png)

2021-06-18 09:51 UTC, takaishi commented on app/mailers/speaker_mailer.rb
> +    mail(to: speaker.email, subject: 'プロポーザルを受け付けました')
おおー、いい感じだ！

2021-06-18 09:51 UTC, takaishi approved these changes

2021-06-18 09:51 UTC, oshiro3 commented on app/mailers/speaker_mailer.rb
> +    mail(to: speaker.email, subject: 'プロポーザルを受け付けました')
略称って Conference クラスから取れなかったので、やるとしたらハードコーディングするしかないんですかね？

2021-06-18 09:51 UTC, merged