Support cfp accepting
cloudnativedaysjp/dreamkast pull request #704
Opened 2021-06-13 02:50 UTC by takaishi

2021-06-28 13:43 UTC, jacopen commented
Proposalsを表示したらエラーになってしまった
![image](https://user-images.githubusercontent.com/79102/123646522-41f67e80-d862-11eb-8037-b69c0ae01d22.png)

2021-06-28 13:46 UTC, jacopen commented
```

142
E, [2021-06-28T13:44:30.132347 #11] ERROR -- : [bed7adf0-ef25-4ca3-994c-f5cd2514b770] Rendering 500 with exception: undefined method `title' for nil:NilClass
141
E, [2021-06-28T13:44:30.132475 #11] ERROR -- : [bed7adf0-ef25-4ca3-994c-f5cd2514b770] /app/app/views/admin/proposals/index.html.erb:26:in `block (3 levels) in _app_views_admin_proposals_index_html_erb__1247922747670878200_331340'
140
/usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/relation/delegation.rb:87:in `each'
```

2021-06-28 13:47 UTC, jacopen requested changes
実際にProposal投稿してみたところReview appsでAdminのProposals落ちてるので確認おねしゃす

2021-06-28 13:57 UTC, jacopen commented
最終的にProposal Modelがやっていることって、採択/不採択を示すbooleanを一つ追加しているだけなんだよね・・・talksに `proposal_accepted` みたいなフィールドを1つ付け加えるのに比べたときのメリットって何になるだろう？

あとProposalsとSpeakersが1:n, TalksとSpeakersも1:n, TalksとProposalsは1:1。
基本的にはproposals_speakersとtalks_speakersは同じになる(スポンサー枠やキーノートは除く)　はずだけど、矛盾する設定も可能っちゃ可能よね(Talk "A"は aさんと紐付けになっているけど、Proposal "A"はbさんと紐付けになるみたいな)。 ちょっとリレーションが複雑になっていて悩ましいなぁと

2021-06-29 00:56 UTC, takaishi commented
> 最終的にProposal Modelがやっていることって、採択/不採択を示すbooleanを一つ追加しているだけなんだよね・・・talksに proposal_accepted みたいなフィールドを1つ付け加えるのに比べたときのメリットって何になるだろう？

このPRではProposalのStatusだけしか持ってないけど、今後採択のための機能を追加していくことも考えられる。そうなると、Talkにあれこれ追加するよりは分けておいた方が良い。また、セッションとプロポーザル自体がドメイン的には別ものだと思っているので分けておいた方がいいと思っている。

リレーションがちとややこしいというのは同意かな。proposal_speakersは今見たらなくてもいい気がしたので再検討する。

2021-07-03 12:32 UTC, jacopen approved these changes

2021-07-03 12:32 UTC, merged