メールの送信等のジョブを非同期で送信できるようにする
cloudnativedaysjp/dreamkast pull request #716
Opened 2021-07-03 12:43 UTC by oshiro3

MailDeliveryJob を作成しメール送信を非同期で実施するように変更しました。#709 

Backend には今回 SQS を使用しており、FIFO キューで想定しています。
ActiveRecordError の場合はジョブを破棄し、それ以外の場合はリトライ( default の wait: 3s, attempts: 5 ) を実施します。

本番に挙げる際には下記3点を考慮する必要があります。

* SQS でキューを作成する
* 環境変数 `SQS_MAIL_QUEUE_URL` を設定する　
* Job ワーカープロセスの設定

2021-07-07 09:45 UTC, takaishi commented on app/controllers/speaker_dashboard/video_registrations_controller.rb
>          rescue => e
非同期化したらここの例外処理は不要になるはずなので消してもらえますか？

2021-07-07 09:48 UTC, takaishi commented
* SQSのキュー作成やSQS_MAIL_QUEUE_URLの指定などは実施済みでしょうか
* （細かいですが）PRがDraft状態なのでレビュー依頼時にはReady for reviewを押しておいてください

2021-07-07 11:38 UTC, oshiro3 commented on app/controllers/speaker_dashboard/video_registrations_controller.rb
>          rescue => e
了解です。
一応 CFP の方も修正しておきました。

2021-07-07 11:40 UTC, oshiro3 commented
SQS のキューの作成はまだで、なので URL も発行できていません。
そのため現在ドラフトで作成しています。

SQS のパラメータとかこちらで設定してしまっても良いんでしょうか？
あと、本番の環境変数ってどこが管理してるんでしょうか？

2021-07-09 09:21 UTC, takaishi commented
> SQS のキューの作成はまだで、なので URL も発行できていません。
> そのため今回に関してはドラフトで作成していました。

あ、なるほど。

> SQS のパラメータとかこちらで設定してしまっても良いんでしょうか？
> あと、本番の環境変数ってどこが管理してるんでしょうか？

設定できるなら設定してもらっても大丈夫かと思います（設定内容は共有してもらった方がよいと思いますが）。
AWSのリソースは https://github.com/cloudopsdays/dreamkast-infra/tree/main/cfn でCFnを使って管理しています。


環境変数は https://github.com/cloudopsdays/dreamkast-infra/blob/main/manifests/app/dreamkast/overlays/production/main/deployment-dreamkast.yaml のように、overlayを使って環境毎に切り替えられるようにしています。 Review Appは https://github.com/cloudopsdays/dreamkast-infra/blob/main/manifests/app/dreamkast/overlays/template/deployment-dreamkast.yaml のテンプレートをもとにしているので、まずはReviewApp用のSQSを作って、URLをReviewAppに反映して動作確認できるようにするのがよいかなと思いました。

2021-07-18 04:27 UTC, oshiro3 commented
@takaishi 
ワーカー以外の設定を https://github.com/cloudnativedaysjp/dreamkast-infra/pull/491 で作成しました。

2021-08-09 03:48 UTC, oshiro3 commented
下記に関して infra の方で P/R がマージされましたので、こちらも確認お願いします。

> 本番に挙げる際には下記3点を考慮する必要があります。
>
>SQS でキューを作成する
環境変数 SQS_MAIL_QUEUE_URL を設定する　
Job ワーカープロセスの設定

2021-08-15 06:41 UTC, takaishi commented
@oshiro3 CIのGitOps、rerunしてもらえますか？infra側の変更をreview appに取り込むには一旦overlayを消して、再度GitOpsのCIを実行しないといけなくて。overlayの方は削除済みです。

2021-08-15 06:57 UTC, oshiro3 commented
@takaishi 
同一の hash で rerun する方法が分からなかったので、main ブランチをマージして Push しました。

2021-08-15 07:19 UTC, takaishi commented
ReviewAppでmail workerが起動してないですね…

```
~/.h/r/dotfiles_castle $ k get pods
NAME                                      READY   STATUS             RESTARTS   AGE
dreamkast-7f46bdc8db-jc7qt                1/1     Running            0          20m
dreamkast-mail--worker-65785c7f98-mv26f   0/1     CrashLoopBackOff   8          20m
dreamkast-mysql-dcc9f76b8-w29f5           1/1     Running            0          20m
dreamkast-redis-5956d4b7d7-2zst2          1/1     Running            0          20m
dreamkast-ui-668c7dc84b-7k9gf             1/1     Running            0          20m
```

2021-09-10 14:33 UTC, oshiro3 commented
deploy不全をGCするためいったんクローズ

2021-09-10 14:36 UTC, oshiro3 commented
GCしたのでreopen

2021-09-11 04:04 UTC, oshiro3 commented
review_app 含め、画面操作からメール配信する機能は現在 cfp の登録・編集だけなのでE2Eの動作確認ができない？

2021-09-11 04:22 UTC, oshiro3 commented
> review_app 含め、画面操作からメール配信する機能は現在 cfp の登録・編集だけなのでE2Eの動作確認ができない？

mail の確認ということで pod の rails console から mailer インスタンスを作成して deliver メソッドが機能することを確認しました。

2021-09-13 10:20 UTC, takaishi requested changes

2021-09-13 10:20 UTC, takaishi commented on app/controllers/speaker_dashboard/video_registrations_controller.rb
>          rescue => e
例外処理が残っているようです。何かのタイミングで戻ったのかな。後、deliver_laterとか使って送信しないとメール送られないですね。

2021-09-13 13:33 UTC, oshiro3 commented on app/controllers/speaker_dashboard/video_registrations_controller.rb
>          rescue => e
ミスオペしてたのかもしれないです。
なぜか deliver メソッド消していたのも修正しました。

2021-09-18 01:07 UTC, takaishi approved these changes

2021-09-19 09:19 UTC, merged