参加者の登録状況をSlackに通知するRakeタスクを追加
cloudnativedaysjp/dreamkast pull request #722
Opened 2021-07-18 08:55 UTC by takaishi

2021-07-22 08:08 UTC, jacopen reviewed
stats_of_registrantsテーブルなんだけど、今はそれぞれのconference_idごとに最新の登録者数が過去のレコードを書き換える形で使われているけども、たとえばレコードをUpdateするのではなくて、毎回新規に追加する形にしたらどうだろうか。

そうすると、後から『どのくらいのペースで人が増えたのか』をグラフにすることもできるなと

2021-07-22 08:08 UTC, jacopen commented on lib/tasks/post_number_of_registrants_to_slack.rake
> +        stats.save!
あ、うそ、仕様を勘違いしていた

2021-07-22 08:29 UTC, takaishi commented
>そうすると、後から『どのくらいのペースで人が増えたのか』をグラフにすることもできるなと

まさにこれをやるためにStatsOfRegistrantは毎回新規作成しているはずだけどなんか間違ってる箇所ある？
グラフ自体はこのPRでは作ってないけど今後作ることを想定してそうしてる

2021-07-22 08:36 UTC, jacopen requested changes

2021-07-22 08:36 UTC, jacopen commented on lib/tasks/post_number_of_registrants_to_slack.rake
> +        stats.save!
なるほど、新規作成するとなるとやっぱりここは変えた方がよさそう。Slackがトラブったりして送れなかったらログがロールバックされて記録されないので、ここはトランザクション外のほうがいいなと

2021-07-22 08:37 UTC, takaishi commented on lib/tasks/post_number_of_registrants_to_slack.rake
> +        stats.save!
なるほど確かに。なおします

2021-07-26 01:49 UTC, jacopen approved these changes

2021-07-26 01:49 UTC, merged