Add cfp form for cndt2021
cloudnativedaysjp/dreamkast pull request #737
Opened 2021-07-31 03:24 UTC by takaishi

2021-07-31 15:15 UTC, takaishi commented
@jacopen CIがDBのマイグレーションまわりで落ちてるけどとりあえずReviewAppは使えるのでレビューヨロ。CICDの方の機能が壊れないかというあたりも見てもらえると。

2021-07-31 17:51 UTC, jacopen commented
CICDのseedを流し込まないとちょっと確認がしづらいな・・・

2021-08-01 00:34 UTC, takaishi commented
seedは入ってると思うけど何を指してる？

2021-08-01 03:43 UTC, jacopen requested changes
動作確認完了。大きな問題はなかったが、CNDT2021側の講演時間が表示できていないのでそこを修正おなしゃす
![image](https://user-images.githubusercontent.com/79102/127758458-b740f36e-56ce-4279-bd7f-479b9215488b.png)

2021-08-01 08:11 UTC, jacopen approved these changes

2021-08-01 08:11 UTC, merged