Add opentelemetry for jeager
cloudnativedaysjp/dreamkast pull request #993
Opened 2021-11-02 17:05 UTC by inductor

https://github.com/cloudnativedaysjp/dreamkast/pull/859

2021-11-02 17:10 UTC, showks-containerdaysjp commented
Review app

https://dreamkast-dk-993.dev.cloudnativedays.jp

2021-11-18 09:25 UTC, inductor commented on config/initializers/open_telemetry_rails.rb
> +      OpenTelemetry::Exporter::Jaeger::AgentExporter.new(host: "jaeger-agent.monitoring", port: 6831)
ローカルでもdocker-composeでjaeger動かしたい場合ここは動的にしたほうがいい

2021-11-19 03:52 UTC, jacopen requested changes

2021-11-19 03:52 UTC, jacopen commented on config/initializers/open_telemetry_rails.rb
> +      OpenTelemetry::Exporter::Jaeger::AgentExporter.new(host: "jaeger-agent.monitoring", port: 6831)
```suggestion
      OpenTelemetry::Exporter::Jaeger::AgentExporter.new(host: ENV['JAEGER_AGENT_ADDR'] || "jaeger-agent.monitoring", port: 6831)
```

2021-11-19 03:55 UTC, jacopen requested changes

2021-11-19 03:55 UTC, jacopen commented on config/initializers/open_telemetry_rails.rb
> +      OpenTelemetry::Exporter::Jaeger::AgentExporter.new(host: ENV['JAEGER_AGENT_ADDR'] || "jaeger-agent.monitoring", port: 6831)
```suggestion
      OpenTelemetry::Exporter::Jaeger::AgentExporter.new(host: ENV["JAEGER_AGENT_ADDR"] || "jaeger-agent.monitoring", port: 6831)
```

2021-11-20 06:10 UTC, merged